/**************************************************************************** 
 * Job:             101_75_15_Extract_CAS_CASIOBOP        A52HJCF1.AR0000SF * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: sasmeta4.dwhgridtest.imb.ru                             * 
 * Port:            8564                                                    * 
 * Location:        /DWH_DWHDDS_STG/Jobs/101_Extract/101_75_CAS/Includes    * 
 *                                                                          * 
 * Server:          SASApp                                A5H5E9KJ.AS000002 * 
 *                                                                          * 
 * Source Tables:   CASIOBOP - CAS.CASIOBOP               A52HJCF1.AH000043 * 
 *                  CASA_CASIOBOP -                       A52HJCF1.AH0002JO * 
 *                   work_stg.CASA_CASIOBOP                                 * 
 * Target Tables:   CASA_CASIOBOP -                       A52HJCF1.AH0002JO * 
 *                   work_stg.CASA_CASIOBOP                                 * 
 *                  CASA_CASIOBOP_ARCH -                  A52HJCF1.AH0000E7 * 
 *                   etl_stg.CASA_CASIOBOP_ARCH                             * 
 *                                                                          * 
 * Generated on:    20 мая 2022 г. 16:30:31 MSK                             * 
 * Generated by:    mb35164@imb.ru                                          * 
 * Version:         SAS Data Integration Studio 4.904                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A52HJCF1.AR0000SF);
%let etls_jobName = %nrquote(101_75_15_Extract_CAS_CASIOBOP);
%let etls_userID = %nrquote(mb35164@imb.ru);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */ 
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8564);
%let metaServer     = %nrquote(sasmeta4.dwhgridtest.imb.ru);

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            Начать модуль                         A52HJCF1.AT0025EL * 
 * Transform:       Начать модуль                                           * 
 * Description:                                                             * 
 *==========================================================================*/ 

%let transformID = %quote(A52HJCF1.AT0025EL);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


/*****************************************************************
*  ВЕРСИЯ:
*     $Id: transform_job_start.sas 4060:d0a33a5b822b 2015-06-19 09:27:21Z rusane $
*
******************************************************************
*  НАЗНАЧЕНИЕ:
*     Регистрирует начало модуля ETL.
*
*  ПАРАМЕТРЫ:
*     нет
*
******************************************************************/

%macro transform_job_start;
   %etl_job_start;
%mend transform_job_start;

%transform_job_start;


%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end Начать модуль **/

/*==========================================================================* 
 * Step:            Выгрузка данных                       A52HJCF1.AT0025EM * 
 * Transform:       Выгрузка данных                                         * 
 * Description:     Выгружает набор из источника, рассчитывает MD5-суммы    * 
 *                   строк.                                                 * 
 *                                                                          * 
 * Source Table:    CASIOBOP - CAS.CASIOBOP               A52HJCF1.AH000043 * 
 * Target Table:    CASA_CASIOBOP -                       A52HJCF1.AH0002JO * 
 *                   work_stg.CASA_CASIOBOP                                 * 
 *==========================================================================*/ 

%let transformID = %quote(A52HJCF1.AT0025EM);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

/* Access the data for CAS  */ 
LIBNAME CAS DB2  DEFER=YES  Datasrc=TC21  SCHEMA=CASMMDWH  AUTHDOMAIN="DB2Auth_srvcas2dwh_TC21_T" ;
%rcSet(&syslibrc); 

/* Access the data for WORK_STG  */ 
LIBNAME work_stg BASE "!ETL_DATA_ROOT/work_stg";
%rcSet(&syslibrc); 

%let SYSLAST = %nrquote(CAS.CASIOBOP); 

%let _INPUT_count = 1; 
%let _INPUT = CAS.CASIOBOP;
%let _INPUT_connect =  DEFER=YES DATASRC=TC21 AUTHDOMAIN="DB2Auth_srvcas2dwh_TC21_T" 
;
%let _INPUT_engine = DB2;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/DWH_DWHDDS_STG/Tables/CAS/CASIOBOP%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let tpIn = CAS.CASIOBOP;
%let tpIn_connect =  DEFER=YES DATASRC=TC21 AUTHDOMAIN="DB2Auth_srvcas2dwh_TC21_T" 
;
%let tpIn_engine = DB2;
%let tpIn_memtype = DATA;
%let tpIn_options = %nrquote();
%let tpIn_alter = %nrquote();
%let tpIn_path = %nrquote(/DWH_DWHDDS_STG/Tables/CAS/CASIOBOP%(Table%));
%let tpIn_type = 1;
%let tpIn_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work_stg.CASA_CASIOBOP;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(COMPRESS = Binary);
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/DWH_DWHDDS_STG/Tables/WORK_STG/CAS/CASA_CASIOBOP%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = NTBRC NTOTP NTDAT NTTID NTSTS NTTLR NTLTP NTLCD NTBRA NTCNU NTCCY 
        NTACD NTASQ NTPFC NTBOC NTVLD NTNAR NTRAT NTRMF NTRTP NTRST NTDRI 
        NTVTP NTVCD NTVAM NTVTR NTDCD NTDCN NTOAT NTODT NTINC NTNVF NTTHR 
        NTTHD NTCAD NTNAS NTNAM NTNAP NTDTP NTDSR NTDNB NTDDT NTDII NTDDC 
        NTCNT NTUSR1 NTUSR2 NTUSR3 NTUSR4 NTTIMI NTTIMA;
%let _OUTPUT_col_count = 51;
%let _OUTPUT_col0_name = NTBRC;
%let _OUTPUT_col0_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col0_length = 3;
%let _OUTPUT_col0_type = $;
%let _OUTPUT_col0_format = $3.;
%let _OUTPUT_col0_informat = $3.;
%let _OUTPUT_col0_label = %nrquote(NTBRC);
%let _OUTPUT_col0_input0 = NTBRC;
%let _OUTPUT_col0_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col0_exp = ;
%let _OUTPUT_col0_input = NTBRC;
%let _OUTPUT_col0_input_count = 1;
%let _OUTPUT_col1_name = NTOTP;
%let _OUTPUT_col1_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col1_length = 2;
%let _OUTPUT_col1_type = $;
%let _OUTPUT_col1_format = $2.;
%let _OUTPUT_col1_informat = $2.;
%let _OUTPUT_col1_label = %nrquote(NTOTP);
%let _OUTPUT_col1_input0 = NTOTP;
%let _OUTPUT_col1_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col1_exp = ;
%let _OUTPUT_col1_input = NTOTP;
%let _OUTPUT_col1_input_count = 1;
%let _OUTPUT_col2_name = NTDAT;
%let _OUTPUT_col2_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col2_length = 8;
%let _OUTPUT_col2_type = ;
%let _OUTPUT_col2_format = 6.;
%let _OUTPUT_col2_informat = 6.;
%let _OUTPUT_col2_label = %nrquote(NTDAT);
%let _OUTPUT_col2_input0 = NTDAT;
%let _OUTPUT_col2_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col2_exp = ;
%let _OUTPUT_col2_input = NTDAT;
%let _OUTPUT_col2_input_count = 1;
%let _OUTPUT_col3_name = NTTID;
%let _OUTPUT_col3_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col3_length = 4;
%let _OUTPUT_col3_type = $;
%let _OUTPUT_col3_format = $4.;
%let _OUTPUT_col3_informat = $4.;
%let _OUTPUT_col3_label = %nrquote(NTTID);
%let _OUTPUT_col3_input0 = NTTID;
%let _OUTPUT_col3_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col3_exp = ;
%let _OUTPUT_col3_input = NTTID;
%let _OUTPUT_col3_input_count = 1;
%let _OUTPUT_col4_name = NTSTS;
%let _OUTPUT_col4_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col4_length = 1;
%let _OUTPUT_col4_type = $;
%let _OUTPUT_col4_format = $1.;
%let _OUTPUT_col4_informat = $1.;
%let _OUTPUT_col4_label = %nrquote(NTSTS);
%let _OUTPUT_col4_input0 = NTSTS;
%let _OUTPUT_col4_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col4_exp = ;
%let _OUTPUT_col4_input = NTSTS;
%let _OUTPUT_col4_input_count = 1;
%let _OUTPUT_col5_name = NTTLR;
%let _OUTPUT_col5_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col5_length = 3;
%let _OUTPUT_col5_type = $;
%let _OUTPUT_col5_format = $3.;
%let _OUTPUT_col5_informat = $3.;
%let _OUTPUT_col5_label = %nrquote(NTTLR);
%let _OUTPUT_col5_input0 = NTTLR;
%let _OUTPUT_col5_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col5_exp = ;
%let _OUTPUT_col5_input = NTTLR;
%let _OUTPUT_col5_input_count = 1;
%let _OUTPUT_col6_name = NTLTP;
%let _OUTPUT_col6_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col6_length = 1;
%let _OUTPUT_col6_type = $;
%let _OUTPUT_col6_format = $1.;
%let _OUTPUT_col6_informat = $1.;
%let _OUTPUT_col6_label = %nrquote(NTLTP);
%let _OUTPUT_col6_input0 = NTLTP;
%let _OUTPUT_col6_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col6_exp = ;
%let _OUTPUT_col6_input = NTLTP;
%let _OUTPUT_col6_input_count = 1;
%let _OUTPUT_col7_name = NTLCD;
%let _OUTPUT_col7_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col7_length = 3;
%let _OUTPUT_col7_type = $;
%let _OUTPUT_col7_format = $3.;
%let _OUTPUT_col7_informat = $3.;
%let _OUTPUT_col7_label = %nrquote(NTLCD);
%let _OUTPUT_col7_input0 = NTLCD;
%let _OUTPUT_col7_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col7_exp = ;
%let _OUTPUT_col7_input = NTLCD;
%let _OUTPUT_col7_input_count = 1;
%let _OUTPUT_col8_name = NTBRA;
%let _OUTPUT_col8_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col8_length = 3;
%let _OUTPUT_col8_type = $;
%let _OUTPUT_col8_format = $3.;
%let _OUTPUT_col8_informat = $3.;
%let _OUTPUT_col8_label = %nrquote(NTBRA);
%let _OUTPUT_col8_input0 = NTBRA;
%let _OUTPUT_col8_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col8_exp = ;
%let _OUTPUT_col8_input = NTBRA;
%let _OUTPUT_col8_input_count = 1;
%let _OUTPUT_col9_name = NTCNU;
%let _OUTPUT_col9_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col9_length = 6;
%let _OUTPUT_col9_type = $;
%let _OUTPUT_col9_format = $6.;
%let _OUTPUT_col9_informat = $6.;
%let _OUTPUT_col9_label = %nrquote(NTCNU);
%let _OUTPUT_col9_input0 = NTCNU;
%let _OUTPUT_col9_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col9_exp = ;
%let _OUTPUT_col9_input = NTCNU;
%let _OUTPUT_col9_input_count = 1;
%let _OUTPUT_col10_name = NTCCY;
%let _OUTPUT_col10_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col10_length = 3;
%let _OUTPUT_col10_type = $;
%let _OUTPUT_col10_format = $3.;
%let _OUTPUT_col10_informat = $3.;
%let _OUTPUT_col10_label = %nrquote(NTCCY);
%let _OUTPUT_col10_input0 = NTCCY;
%let _OUTPUT_col10_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col10_exp = ;
%let _OUTPUT_col10_input = NTCCY;
%let _OUTPUT_col10_input_count = 1;
%let _OUTPUT_col11_name = NTACD;
%let _OUTPUT_col11_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col11_length = 8;
%let _OUTPUT_col11_type = ;
%let _OUTPUT_col11_format = 5.;
%let _OUTPUT_col11_informat = 5.;
%let _OUTPUT_col11_label = %nrquote(NTACD);
%let _OUTPUT_col11_input0 = NTACD;
%let _OUTPUT_col11_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col11_exp = ;
%let _OUTPUT_col11_input = NTACD;
%let _OUTPUT_col11_input_count = 1;
%let _OUTPUT_col12_name = NTASQ;
%let _OUTPUT_col12_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col12_length = 8;
%let _OUTPUT_col12_type = ;
%let _OUTPUT_col12_format = 3.;
%let _OUTPUT_col12_informat = 3.;
%let _OUTPUT_col12_label = %nrquote(NTASQ);
%let _OUTPUT_col12_input0 = NTASQ;
%let _OUTPUT_col12_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col12_exp = ;
%let _OUTPUT_col12_input = NTASQ;
%let _OUTPUT_col12_input_count = 1;
%let _OUTPUT_col13_name = NTPFC;
%let _OUTPUT_col13_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col13_length = 4;
%let _OUTPUT_col13_type = $;
%let _OUTPUT_col13_format = $4.;
%let _OUTPUT_col13_informat = $4.;
%let _OUTPUT_col13_label = %nrquote(NTPFC);
%let _OUTPUT_col13_input0 = NTPFC;
%let _OUTPUT_col13_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col13_exp = ;
%let _OUTPUT_col13_input = NTPFC;
%let _OUTPUT_col13_input_count = 1;
%let _OUTPUT_col14_name = NTBOC;
%let _OUTPUT_col14_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col14_length = 2;
%let _OUTPUT_col14_type = $;
%let _OUTPUT_col14_format = $2.;
%let _OUTPUT_col14_informat = $2.;
%let _OUTPUT_col14_label = %nrquote(NTBOC);
%let _OUTPUT_col14_input0 = NTBOC;
%let _OUTPUT_col14_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col14_exp = ;
%let _OUTPUT_col14_input = NTBOC;
%let _OUTPUT_col14_input_count = 1;
%let _OUTPUT_col15_name = NTVLD;
%let _OUTPUT_col15_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col15_length = 8;
%let _OUTPUT_col15_type = ;
%let _OUTPUT_col15_format = 6.;
%let _OUTPUT_col15_informat = 6.;
%let _OUTPUT_col15_label = %nrquote(NTVLD);
%let _OUTPUT_col15_input0 = NTVLD;
%let _OUTPUT_col15_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col15_exp = ;
%let _OUTPUT_col15_input = NTVLD;
%let _OUTPUT_col15_input_count = 1;
%let _OUTPUT_col16_name = NTNAR;
%let _OUTPUT_col16_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col16_length = 70;
%let _OUTPUT_col16_type = $;
%let _OUTPUT_col16_format = $70.;
%let _OUTPUT_col16_informat = $70.;
%let _OUTPUT_col16_label = %nrquote(NTNAR);
%let _OUTPUT_col16_input0 = NTNAR;
%let _OUTPUT_col16_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col16_exp = ;
%let _OUTPUT_col16_input = NTNAR;
%let _OUTPUT_col16_input_count = 1;
%let _OUTPUT_col17_name = NTRAT;
%let _OUTPUT_col17_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col17_length = 8;
%let _OUTPUT_col17_type = ;
%let _OUTPUT_col17_format = 15.8;
%let _OUTPUT_col17_informat = 15.8;
%let _OUTPUT_col17_label = %nrquote(NTRAT);
%let _OUTPUT_col17_input0 = NTRAT;
%let _OUTPUT_col17_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col17_exp = ;
%let _OUTPUT_col17_input = NTRAT;
%let _OUTPUT_col17_input_count = 1;
%let _OUTPUT_col18_name = NTRMF;
%let _OUTPUT_col18_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col18_length = 1;
%let _OUTPUT_col18_type = $;
%let _OUTPUT_col18_format = $1.;
%let _OUTPUT_col18_informat = $1.;
%let _OUTPUT_col18_label = %nrquote(NTRMF);
%let _OUTPUT_col18_input0 = NTRMF;
%let _OUTPUT_col18_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col18_exp = ;
%let _OUTPUT_col18_input = NTRMF;
%let _OUTPUT_col18_input_count = 1;
%let _OUTPUT_col19_name = NTRTP;
%let _OUTPUT_col19_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col19_length = 1;
%let _OUTPUT_col19_type = $;
%let _OUTPUT_col19_format = $1.;
%let _OUTPUT_col19_informat = $1.;
%let _OUTPUT_col19_label = %nrquote(NTRTP);
%let _OUTPUT_col19_input0 = NTRTP;
%let _OUTPUT_col19_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col19_exp = ;
%let _OUTPUT_col19_input = NTRTP;
%let _OUTPUT_col19_input_count = 1;
%let _OUTPUT_col20_name = NTRST;
%let _OUTPUT_col20_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col20_length = 1;
%let _OUTPUT_col20_type = $;
%let _OUTPUT_col20_format = $1.;
%let _OUTPUT_col20_informat = $1.;
%let _OUTPUT_col20_label = %nrquote(NTRST);
%let _OUTPUT_col20_input0 = NTRST;
%let _OUTPUT_col20_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col20_exp = ;
%let _OUTPUT_col20_input = NTRST;
%let _OUTPUT_col20_input_count = 1;
%let _OUTPUT_col21_name = NTDRI;
%let _OUTPUT_col21_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col21_length = 1;
%let _OUTPUT_col21_type = $;
%let _OUTPUT_col21_format = $1.;
%let _OUTPUT_col21_informat = $1.;
%let _OUTPUT_col21_label = %nrquote(NTDRI);
%let _OUTPUT_col21_input0 = NTDRI;
%let _OUTPUT_col21_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col21_exp = ;
%let _OUTPUT_col21_input = NTDRI;
%let _OUTPUT_col21_input_count = 1;
%let _OUTPUT_col22_name = NTVTP;
%let _OUTPUT_col22_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col22_length = 1;
%let _OUTPUT_col22_type = $;
%let _OUTPUT_col22_format = $1.;
%let _OUTPUT_col22_informat = $1.;
%let _OUTPUT_col22_label = %nrquote(NTVTP);
%let _OUTPUT_col22_input0 = NTVTP;
%let _OUTPUT_col22_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col22_exp = ;
%let _OUTPUT_col22_input = NTVTP;
%let _OUTPUT_col22_input_count = 1;
%let _OUTPUT_col23_name = NTVCD;
%let _OUTPUT_col23_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col23_length = 3;
%let _OUTPUT_col23_type = $;
%let _OUTPUT_col23_format = $3.;
%let _OUTPUT_col23_informat = $3.;
%let _OUTPUT_col23_label = %nrquote(NTVCD);
%let _OUTPUT_col23_input0 = NTVCD;
%let _OUTPUT_col23_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col23_exp = ;
%let _OUTPUT_col23_input = NTVCD;
%let _OUTPUT_col23_input_count = 1;
%let _OUTPUT_col24_name = NTVAM;
%let _OUTPUT_col24_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col24_length = 8;
%let _OUTPUT_col24_type = ;
%let _OUTPUT_col24_format = 4.;
%let _OUTPUT_col24_informat = 4.;
%let _OUTPUT_col24_label = %nrquote(NTVAM);
%let _OUTPUT_col24_input0 = NTVAM;
%let _OUTPUT_col24_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col24_exp = ;
%let _OUTPUT_col24_input = NTVAM;
%let _OUTPUT_col24_input_count = 1;
%let _OUTPUT_col25_name = NTVTR;
%let _OUTPUT_col25_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col25_length = 3;
%let _OUTPUT_col25_type = $;
%let _OUTPUT_col25_format = $3.;
%let _OUTPUT_col25_informat = $3.;
%let _OUTPUT_col25_label = %nrquote(NTVTR);
%let _OUTPUT_col25_input0 = NTVTR;
%let _OUTPUT_col25_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col25_exp = ;
%let _OUTPUT_col25_input = NTVTR;
%let _OUTPUT_col25_input_count = 1;
%let _OUTPUT_col26_name = NTDCD;
%let _OUTPUT_col26_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col26_length = 3;
%let _OUTPUT_col26_type = $;
%let _OUTPUT_col26_format = $3.;
%let _OUTPUT_col26_informat = $3.;
%let _OUTPUT_col26_label = %nrquote(NTDCD);
%let _OUTPUT_col26_input0 = NTDCD;
%let _OUTPUT_col26_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col26_exp = ;
%let _OUTPUT_col26_input = NTDCD;
%let _OUTPUT_col26_input_count = 1;
%let _OUTPUT_col27_name = NTDCN;
%let _OUTPUT_col27_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col27_length = 11;
%let _OUTPUT_col27_type = $;
%let _OUTPUT_col27_format = $11.;
%let _OUTPUT_col27_informat = $11.;
%let _OUTPUT_col27_label = %nrquote(NTDCN);
%let _OUTPUT_col27_input0 = NTDCN;
%let _OUTPUT_col27_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col27_exp = ;
%let _OUTPUT_col27_input = NTDCN;
%let _OUTPUT_col27_input_count = 1;
%let _OUTPUT_col28_name = NTOAT;
%let _OUTPUT_col28_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col28_length = 8;
%let _OUTPUT_col28_type = ;
%let _OUTPUT_col28_format = 14.;
%let _OUTPUT_col28_informat = 14.;
%let _OUTPUT_col28_label = %nrquote(NTOAT);
%let _OUTPUT_col28_input0 = NTOAT;
%let _OUTPUT_col28_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col28_exp = ;
%let _OUTPUT_col28_input = NTOAT;
%let _OUTPUT_col28_input_count = 1;
%let _OUTPUT_col29_name = NTODT;
%let _OUTPUT_col29_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col29_length = 4;
%let _OUTPUT_col29_type = $;
%let _OUTPUT_col29_format = $4.;
%let _OUTPUT_col29_informat = $4.;
%let _OUTPUT_col29_label = %nrquote(NTODT);
%let _OUTPUT_col29_input0 = NTODT;
%let _OUTPUT_col29_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col29_exp = ;
%let _OUTPUT_col29_input = NTODT;
%let _OUTPUT_col29_input_count = 1;
%let _OUTPUT_col30_name = NTINC;
%let _OUTPUT_col30_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col30_length = 1;
%let _OUTPUT_col30_type = $;
%let _OUTPUT_col30_format = $1.;
%let _OUTPUT_col30_informat = $1.;
%let _OUTPUT_col30_label = %nrquote(NTINC);
%let _OUTPUT_col30_input0 = NTINC;
%let _OUTPUT_col30_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col30_exp = ;
%let _OUTPUT_col30_input = NTINC;
%let _OUTPUT_col30_input_count = 1;
%let _OUTPUT_col31_name = NTNVF;
%let _OUTPUT_col31_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col31_length = 1;
%let _OUTPUT_col31_type = $;
%let _OUTPUT_col31_format = $1.;
%let _OUTPUT_col31_informat = $1.;
%let _OUTPUT_col31_label = %nrquote(NTNVF);
%let _OUTPUT_col31_input0 = NTNVF;
%let _OUTPUT_col31_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col31_exp = ;
%let _OUTPUT_col31_input = NTNVF;
%let _OUTPUT_col31_input_count = 1;
%let _OUTPUT_col32_name = NTTHR;
%let _OUTPUT_col32_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col32_length = 10;
%let _OUTPUT_col32_type = $;
%let _OUTPUT_col32_format = $10.;
%let _OUTPUT_col32_informat = $10.;
%let _OUTPUT_col32_label = %nrquote(NTTHR);
%let _OUTPUT_col32_input0 = NTTHR;
%let _OUTPUT_col32_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col32_exp = ;
%let _OUTPUT_col32_input = NTTHR;
%let _OUTPUT_col32_input_count = 1;
%let _OUTPUT_col33_name = NTTHD;
%let _OUTPUT_col33_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col33_length = 8;
%let _OUTPUT_col33_type = ;
%let _OUTPUT_col33_format = 6.;
%let _OUTPUT_col33_informat = 6.;
%let _OUTPUT_col33_label = %nrquote(NTTHD);
%let _OUTPUT_col33_input0 = NTTHD;
%let _OUTPUT_col33_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col33_exp = ;
%let _OUTPUT_col33_input = NTTHD;
%let _OUTPUT_col33_input_count = 1;
%let _OUTPUT_col34_name = NTCAD;
%let _OUTPUT_col34_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col34_length = 1;
%let _OUTPUT_col34_type = $;
%let _OUTPUT_col34_format = $1.;
%let _OUTPUT_col34_informat = $1.;
%let _OUTPUT_col34_label = %nrquote(NTCAD);
%let _OUTPUT_col34_input0 = NTCAD;
%let _OUTPUT_col34_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col34_exp = ;
%let _OUTPUT_col34_input = NTCAD;
%let _OUTPUT_col34_input_count = 1;
%let _OUTPUT_col35_name = NTNAS;
%let _OUTPUT_col35_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col35_length = 30;
%let _OUTPUT_col35_type = $;
%let _OUTPUT_col35_format = $30.;
%let _OUTPUT_col35_informat = $30.;
%let _OUTPUT_col35_label = %nrquote(NTNAS);
%let _OUTPUT_col35_input0 = NTNAS;
%let _OUTPUT_col35_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col35_exp = ;
%let _OUTPUT_col35_input = NTNAS;
%let _OUTPUT_col35_input_count = 1;
%let _OUTPUT_col36_name = NTNAM;
%let _OUTPUT_col36_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col36_length = 30;
%let _OUTPUT_col36_type = $;
%let _OUTPUT_col36_format = $30.;
%let _OUTPUT_col36_informat = $30.;
%let _OUTPUT_col36_label = %nrquote(NTNAM);
%let _OUTPUT_col36_input0 = NTNAM;
%let _OUTPUT_col36_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col36_exp = ;
%let _OUTPUT_col36_input = NTNAM;
%let _OUTPUT_col36_input_count = 1;
%let _OUTPUT_col37_name = NTNAP;
%let _OUTPUT_col37_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col37_length = 30;
%let _OUTPUT_col37_type = $;
%let _OUTPUT_col37_format = $30.;
%let _OUTPUT_col37_informat = $30.;
%let _OUTPUT_col37_label = %nrquote(NTNAP);
%let _OUTPUT_col37_input0 = NTNAP;
%let _OUTPUT_col37_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col37_exp = ;
%let _OUTPUT_col37_input = NTNAP;
%let _OUTPUT_col37_input_count = 1;
%let _OUTPUT_col38_name = NTDTP;
%let _OUTPUT_col38_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col38_length = 2;
%let _OUTPUT_col38_type = $;
%let _OUTPUT_col38_format = $2.;
%let _OUTPUT_col38_informat = $2.;
%let _OUTPUT_col38_label = %nrquote(NTDTP);
%let _OUTPUT_col38_input0 = NTDTP;
%let _OUTPUT_col38_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col38_exp = ;
%let _OUTPUT_col38_input = NTDTP;
%let _OUTPUT_col38_input_count = 1;
%let _OUTPUT_col39_name = NTDSR;
%let _OUTPUT_col39_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col39_length = 10;
%let _OUTPUT_col39_type = $;
%let _OUTPUT_col39_format = $10.;
%let _OUTPUT_col39_informat = $10.;
%let _OUTPUT_col39_label = %nrquote(NTDSR);
%let _OUTPUT_col39_input0 = NTDSR;
%let _OUTPUT_col39_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col39_exp = ;
%let _OUTPUT_col39_input = NTDSR;
%let _OUTPUT_col39_input_count = 1;
%let _OUTPUT_col40_name = NTDNB;
%let _OUTPUT_col40_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col40_length = 20;
%let _OUTPUT_col40_type = $;
%let _OUTPUT_col40_format = $20.;
%let _OUTPUT_col40_informat = $20.;
%let _OUTPUT_col40_label = %nrquote(NTDNB);
%let _OUTPUT_col40_input0 = NTDNB;
%let _OUTPUT_col40_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col40_exp = ;
%let _OUTPUT_col40_input = NTDNB;
%let _OUTPUT_col40_input_count = 1;
%let _OUTPUT_col41_name = NTDDT;
%let _OUTPUT_col41_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col41_length = 10;
%let _OUTPUT_col41_type = $;
%let _OUTPUT_col41_format = $10.;
%let _OUTPUT_col41_informat = $10.;
%let _OUTPUT_col41_label = %nrquote(NTDDT);
%let _OUTPUT_col41_input0 = NTDDT;
%let _OUTPUT_col41_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col41_exp = ;
%let _OUTPUT_col41_input = NTDDT;
%let _OUTPUT_col41_input_count = 1;
%let _OUTPUT_col42_name = NTDII;
%let _OUTPUT_col42_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col42_length = 60;
%let _OUTPUT_col42_type = $;
%let _OUTPUT_col42_format = $60.;
%let _OUTPUT_col42_informat = $60.;
%let _OUTPUT_col42_label = %nrquote(NTDII);
%let _OUTPUT_col42_input0 = NTDII;
%let _OUTPUT_col42_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col42_exp = ;
%let _OUTPUT_col42_input = NTDII;
%let _OUTPUT_col42_input_count = 1;
%let _OUTPUT_col43_name = NTDDC;
%let _OUTPUT_col43_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col43_length = 15;
%let _OUTPUT_col43_type = $;
%let _OUTPUT_col43_format = $15.;
%let _OUTPUT_col43_informat = $15.;
%let _OUTPUT_col43_label = %nrquote(NTDDC);
%let _OUTPUT_col43_input0 = NTDDC;
%let _OUTPUT_col43_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col43_exp = ;
%let _OUTPUT_col43_input = NTDDC;
%let _OUTPUT_col43_input_count = 1;
%let _OUTPUT_col44_name = NTCNT;
%let _OUTPUT_col44_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col44_length = 2;
%let _OUTPUT_col44_type = $;
%let _OUTPUT_col44_format = $2.;
%let _OUTPUT_col44_informat = $2.;
%let _OUTPUT_col44_label = %nrquote(NTCNT);
%let _OUTPUT_col44_input0 = NTCNT;
%let _OUTPUT_col44_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col44_exp = ;
%let _OUTPUT_col44_input = NTCNT;
%let _OUTPUT_col44_input_count = 1;
%let _OUTPUT_col45_name = NTUSR1;
%let _OUTPUT_col45_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col45_length = 10;
%let _OUTPUT_col45_type = $;
%let _OUTPUT_col45_format = $10.;
%let _OUTPUT_col45_informat = $10.;
%let _OUTPUT_col45_label = %nrquote(NTUSR1);
%let _OUTPUT_col45_input0 = NTUSR1;
%let _OUTPUT_col45_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col45_exp = ;
%let _OUTPUT_col45_input = NTUSR1;
%let _OUTPUT_col45_input_count = 1;
%let _OUTPUT_col46_name = NTUSR2;
%let _OUTPUT_col46_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col46_length = 10;
%let _OUTPUT_col46_type = $;
%let _OUTPUT_col46_format = $10.;
%let _OUTPUT_col46_informat = $10.;
%let _OUTPUT_col46_label = %nrquote(NTUSR2);
%let _OUTPUT_col46_input0 = NTUSR2;
%let _OUTPUT_col46_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col46_exp = ;
%let _OUTPUT_col46_input = NTUSR2;
%let _OUTPUT_col46_input_count = 1;
%let _OUTPUT_col47_name = NTUSR3;
%let _OUTPUT_col47_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col47_length = 10;
%let _OUTPUT_col47_type = $;
%let _OUTPUT_col47_format = $10.;
%let _OUTPUT_col47_informat = $10.;
%let _OUTPUT_col47_label = %nrquote(NTUSR3);
%let _OUTPUT_col47_input0 = NTUSR3;
%let _OUTPUT_col47_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col47_exp = ;
%let _OUTPUT_col47_input = NTUSR3;
%let _OUTPUT_col47_input_count = 1;
%let _OUTPUT_col48_name = NTUSR4;
%let _OUTPUT_col48_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col48_length = 10;
%let _OUTPUT_col48_type = $;
%let _OUTPUT_col48_format = $10.;
%let _OUTPUT_col48_informat = $10.;
%let _OUTPUT_col48_label = %nrquote(NTUSR4);
%let _OUTPUT_col48_input0 = NTUSR4;
%let _OUTPUT_col48_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col48_exp = ;
%let _OUTPUT_col48_input = NTUSR4;
%let _OUTPUT_col48_input_count = 1;
%let _OUTPUT_col49_name = NTTIMI;
%let _OUTPUT_col49_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col49_length = 8;
%let _OUTPUT_col49_type = ;
%let _OUTPUT_col49_format = 7.;
%let _OUTPUT_col49_informat = 7.;
%let _OUTPUT_col49_label = %nrquote(NTTIMI);
%let _OUTPUT_col49_input0 = NTTIMI;
%let _OUTPUT_col49_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col49_exp = ;
%let _OUTPUT_col49_input = NTTIMI;
%let _OUTPUT_col49_input_count = 1;
%let _OUTPUT_col50_name = NTTIMA;
%let _OUTPUT_col50_table = work_stg.CASA_CASIOBOP;
%let _OUTPUT_col50_length = 8;
%let _OUTPUT_col50_type = ;
%let _OUTPUT_col50_format = 7.;
%let _OUTPUT_col50_informat = 7.;
%let _OUTPUT_col50_label = %nrquote(NTTIMA);
%let _OUTPUT_col50_input0 = NTTIMA;
%let _OUTPUT_col50_input0_table = CAS.CASIOBOP;
%let _OUTPUT_col50_exp = ;
%let _OUTPUT_col50_input = NTTIMA;
%let _OUTPUT_col50_input_count = 1;

%let tpOutData = work_stg.CASA_CASIOBOP;
%let tpOutData_connect = null;
%let tpOutData_engine = BASE;
%let tpOutData_memtype = DATA;
%let tpOutData_options = %nrquote(COMPRESS = Binary);
%let tpOutData_alter = %nrquote();
%let tpOutData_path = %nrquote(/DWH_DWHDDS_STG/Tables/WORK_STG/CAS/CASA_CASIOBOP%(Table%));
%let tpOutData_type = 1;
%let tpOutData_label = %nrquote();
/* List of target columns to keep  */ 
%let tpOutData_keep = NTBRC NTOTP NTDAT NTTID NTSTS NTTLR NTLTP NTLCD NTBRA NTCNU NTCCY 
        NTACD NTASQ NTPFC NTBOC NTVLD NTNAR NTRAT NTRMF NTRTP NTRST NTDRI 
        NTVTP NTVCD NTVAM NTVTR NTDCD NTDCN NTOAT NTODT NTINC NTNVF NTTHR 
        NTTHD NTCAD NTNAS NTNAM NTNAP NTDTP NTDSR NTDNB NTDDT NTDII NTDDC 
        NTCNT NTUSR1 NTUSR2 NTUSR3 NTUSR4 NTTIMI NTTIMA;
%let tpOutData_col_count = 51;
%let tpOutData_col0_name = NTBRC;
%let tpOutData_col0_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col0_length = 3;
%let tpOutData_col0_type = $;
%let tpOutData_col0_format = $3.;
%let tpOutData_col0_informat = $3.;
%let tpOutData_col0_label = %nrquote(NTBRC);
%let tpOutData_col0_input0 = NTBRC;
%let tpOutData_col0_input0_table = CAS.CASIOBOP;
%let tpOutData_col0_exp = ;
%let tpOutData_col0_input = NTBRC;
%let tpOutData_col0_input_count = 1;
%let tpOutData_col1_name = NTOTP;
%let tpOutData_col1_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col1_length = 2;
%let tpOutData_col1_type = $;
%let tpOutData_col1_format = $2.;
%let tpOutData_col1_informat = $2.;
%let tpOutData_col1_label = %nrquote(NTOTP);
%let tpOutData_col1_input0 = NTOTP;
%let tpOutData_col1_input0_table = CAS.CASIOBOP;
%let tpOutData_col1_exp = ;
%let tpOutData_col1_input = NTOTP;
%let tpOutData_col1_input_count = 1;
%let tpOutData_col2_name = NTDAT;
%let tpOutData_col2_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col2_length = 8;
%let tpOutData_col2_type = ;
%let tpOutData_col2_format = 6.;
%let tpOutData_col2_informat = 6.;
%let tpOutData_col2_label = %nrquote(NTDAT);
%let tpOutData_col2_input0 = NTDAT;
%let tpOutData_col2_input0_table = CAS.CASIOBOP;
%let tpOutData_col2_exp = ;
%let tpOutData_col2_input = NTDAT;
%let tpOutData_col2_input_count = 1;
%let tpOutData_col3_name = NTTID;
%let tpOutData_col3_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col3_length = 4;
%let tpOutData_col3_type = $;
%let tpOutData_col3_format = $4.;
%let tpOutData_col3_informat = $4.;
%let tpOutData_col3_label = %nrquote(NTTID);
%let tpOutData_col3_input0 = NTTID;
%let tpOutData_col3_input0_table = CAS.CASIOBOP;
%let tpOutData_col3_exp = ;
%let tpOutData_col3_input = NTTID;
%let tpOutData_col3_input_count = 1;
%let tpOutData_col4_name = NTSTS;
%let tpOutData_col4_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col4_length = 1;
%let tpOutData_col4_type = $;
%let tpOutData_col4_format = $1.;
%let tpOutData_col4_informat = $1.;
%let tpOutData_col4_label = %nrquote(NTSTS);
%let tpOutData_col4_input0 = NTSTS;
%let tpOutData_col4_input0_table = CAS.CASIOBOP;
%let tpOutData_col4_exp = ;
%let tpOutData_col4_input = NTSTS;
%let tpOutData_col4_input_count = 1;
%let tpOutData_col5_name = NTTLR;
%let tpOutData_col5_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col5_length = 3;
%let tpOutData_col5_type = $;
%let tpOutData_col5_format = $3.;
%let tpOutData_col5_informat = $3.;
%let tpOutData_col5_label = %nrquote(NTTLR);
%let tpOutData_col5_input0 = NTTLR;
%let tpOutData_col5_input0_table = CAS.CASIOBOP;
%let tpOutData_col5_exp = ;
%let tpOutData_col5_input = NTTLR;
%let tpOutData_col5_input_count = 1;
%let tpOutData_col6_name = NTLTP;
%let tpOutData_col6_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col6_length = 1;
%let tpOutData_col6_type = $;
%let tpOutData_col6_format = $1.;
%let tpOutData_col6_informat = $1.;
%let tpOutData_col6_label = %nrquote(NTLTP);
%let tpOutData_col6_input0 = NTLTP;
%let tpOutData_col6_input0_table = CAS.CASIOBOP;
%let tpOutData_col6_exp = ;
%let tpOutData_col6_input = NTLTP;
%let tpOutData_col6_input_count = 1;
%let tpOutData_col7_name = NTLCD;
%let tpOutData_col7_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col7_length = 3;
%let tpOutData_col7_type = $;
%let tpOutData_col7_format = $3.;
%let tpOutData_col7_informat = $3.;
%let tpOutData_col7_label = %nrquote(NTLCD);
%let tpOutData_col7_input0 = NTLCD;
%let tpOutData_col7_input0_table = CAS.CASIOBOP;
%let tpOutData_col7_exp = ;
%let tpOutData_col7_input = NTLCD;
%let tpOutData_col7_input_count = 1;
%let tpOutData_col8_name = NTBRA;
%let tpOutData_col8_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col8_length = 3;
%let tpOutData_col8_type = $;
%let tpOutData_col8_format = $3.;
%let tpOutData_col8_informat = $3.;
%let tpOutData_col8_label = %nrquote(NTBRA);
%let tpOutData_col8_input0 = NTBRA;
%let tpOutData_col8_input0_table = CAS.CASIOBOP;
%let tpOutData_col8_exp = ;
%let tpOutData_col8_input = NTBRA;
%let tpOutData_col8_input_count = 1;
%let tpOutData_col9_name = NTCNU;
%let tpOutData_col9_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col9_length = 6;
%let tpOutData_col9_type = $;
%let tpOutData_col9_format = $6.;
%let tpOutData_col9_informat = $6.;
%let tpOutData_col9_label = %nrquote(NTCNU);
%let tpOutData_col9_input0 = NTCNU;
%let tpOutData_col9_input0_table = CAS.CASIOBOP;
%let tpOutData_col9_exp = ;
%let tpOutData_col9_input = NTCNU;
%let tpOutData_col9_input_count = 1;
%let tpOutData_col10_name = NTCCY;
%let tpOutData_col10_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col10_length = 3;
%let tpOutData_col10_type = $;
%let tpOutData_col10_format = $3.;
%let tpOutData_col10_informat = $3.;
%let tpOutData_col10_label = %nrquote(NTCCY);
%let tpOutData_col10_input0 = NTCCY;
%let tpOutData_col10_input0_table = CAS.CASIOBOP;
%let tpOutData_col10_exp = ;
%let tpOutData_col10_input = NTCCY;
%let tpOutData_col10_input_count = 1;
%let tpOutData_col11_name = NTACD;
%let tpOutData_col11_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col11_length = 8;
%let tpOutData_col11_type = ;
%let tpOutData_col11_format = 5.;
%let tpOutData_col11_informat = 5.;
%let tpOutData_col11_label = %nrquote(NTACD);
%let tpOutData_col11_input0 = NTACD;
%let tpOutData_col11_input0_table = CAS.CASIOBOP;
%let tpOutData_col11_exp = ;
%let tpOutData_col11_input = NTACD;
%let tpOutData_col11_input_count = 1;
%let tpOutData_col12_name = NTASQ;
%let tpOutData_col12_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col12_length = 8;
%let tpOutData_col12_type = ;
%let tpOutData_col12_format = 3.;
%let tpOutData_col12_informat = 3.;
%let tpOutData_col12_label = %nrquote(NTASQ);
%let tpOutData_col12_input0 = NTASQ;
%let tpOutData_col12_input0_table = CAS.CASIOBOP;
%let tpOutData_col12_exp = ;
%let tpOutData_col12_input = NTASQ;
%let tpOutData_col12_input_count = 1;
%let tpOutData_col13_name = NTPFC;
%let tpOutData_col13_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col13_length = 4;
%let tpOutData_col13_type = $;
%let tpOutData_col13_format = $4.;
%let tpOutData_col13_informat = $4.;
%let tpOutData_col13_label = %nrquote(NTPFC);
%let tpOutData_col13_input0 = NTPFC;
%let tpOutData_col13_input0_table = CAS.CASIOBOP;
%let tpOutData_col13_exp = ;
%let tpOutData_col13_input = NTPFC;
%let tpOutData_col13_input_count = 1;
%let tpOutData_col14_name = NTBOC;
%let tpOutData_col14_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col14_length = 2;
%let tpOutData_col14_type = $;
%let tpOutData_col14_format = $2.;
%let tpOutData_col14_informat = $2.;
%let tpOutData_col14_label = %nrquote(NTBOC);
%let tpOutData_col14_input0 = NTBOC;
%let tpOutData_col14_input0_table = CAS.CASIOBOP;
%let tpOutData_col14_exp = ;
%let tpOutData_col14_input = NTBOC;
%let tpOutData_col14_input_count = 1;
%let tpOutData_col15_name = NTVLD;
%let tpOutData_col15_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col15_length = 8;
%let tpOutData_col15_type = ;
%let tpOutData_col15_format = 6.;
%let tpOutData_col15_informat = 6.;
%let tpOutData_col15_label = %nrquote(NTVLD);
%let tpOutData_col15_input0 = NTVLD;
%let tpOutData_col15_input0_table = CAS.CASIOBOP;
%let tpOutData_col15_exp = ;
%let tpOutData_col15_input = NTVLD;
%let tpOutData_col15_input_count = 1;
%let tpOutData_col16_name = NTNAR;
%let tpOutData_col16_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col16_length = 70;
%let tpOutData_col16_type = $;
%let tpOutData_col16_format = $70.;
%let tpOutData_col16_informat = $70.;
%let tpOutData_col16_label = %nrquote(NTNAR);
%let tpOutData_col16_input0 = NTNAR;
%let tpOutData_col16_input0_table = CAS.CASIOBOP;
%let tpOutData_col16_exp = ;
%let tpOutData_col16_input = NTNAR;
%let tpOutData_col16_input_count = 1;
%let tpOutData_col17_name = NTRAT;
%let tpOutData_col17_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col17_length = 8;
%let tpOutData_col17_type = ;
%let tpOutData_col17_format = 15.8;
%let tpOutData_col17_informat = 15.8;
%let tpOutData_col17_label = %nrquote(NTRAT);
%let tpOutData_col17_input0 = NTRAT;
%let tpOutData_col17_input0_table = CAS.CASIOBOP;
%let tpOutData_col17_exp = ;
%let tpOutData_col17_input = NTRAT;
%let tpOutData_col17_input_count = 1;
%let tpOutData_col18_name = NTRMF;
%let tpOutData_col18_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col18_length = 1;
%let tpOutData_col18_type = $;
%let tpOutData_col18_format = $1.;
%let tpOutData_col18_informat = $1.;
%let tpOutData_col18_label = %nrquote(NTRMF);
%let tpOutData_col18_input0 = NTRMF;
%let tpOutData_col18_input0_table = CAS.CASIOBOP;
%let tpOutData_col18_exp = ;
%let tpOutData_col18_input = NTRMF;
%let tpOutData_col18_input_count = 1;
%let tpOutData_col19_name = NTRTP;
%let tpOutData_col19_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col19_length = 1;
%let tpOutData_col19_type = $;
%let tpOutData_col19_format = $1.;
%let tpOutData_col19_informat = $1.;
%let tpOutData_col19_label = %nrquote(NTRTP);
%let tpOutData_col19_input0 = NTRTP;
%let tpOutData_col19_input0_table = CAS.CASIOBOP;
%let tpOutData_col19_exp = ;
%let tpOutData_col19_input = NTRTP;
%let tpOutData_col19_input_count = 1;
%let tpOutData_col20_name = NTRST;
%let tpOutData_col20_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col20_length = 1;
%let tpOutData_col20_type = $;
%let tpOutData_col20_format = $1.;
%let tpOutData_col20_informat = $1.;
%let tpOutData_col20_label = %nrquote(NTRST);
%let tpOutData_col20_input0 = NTRST;
%let tpOutData_col20_input0_table = CAS.CASIOBOP;
%let tpOutData_col20_exp = ;
%let tpOutData_col20_input = NTRST;
%let tpOutData_col20_input_count = 1;
%let tpOutData_col21_name = NTDRI;
%let tpOutData_col21_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col21_length = 1;
%let tpOutData_col21_type = $;
%let tpOutData_col21_format = $1.;
%let tpOutData_col21_informat = $1.;
%let tpOutData_col21_label = %nrquote(NTDRI);
%let tpOutData_col21_input0 = NTDRI;
%let tpOutData_col21_input0_table = CAS.CASIOBOP;
%let tpOutData_col21_exp = ;
%let tpOutData_col21_input = NTDRI;
%let tpOutData_col21_input_count = 1;
%let tpOutData_col22_name = NTVTP;
%let tpOutData_col22_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col22_length = 1;
%let tpOutData_col22_type = $;
%let tpOutData_col22_format = $1.;
%let tpOutData_col22_informat = $1.;
%let tpOutData_col22_label = %nrquote(NTVTP);
%let tpOutData_col22_input0 = NTVTP;
%let tpOutData_col22_input0_table = CAS.CASIOBOP;
%let tpOutData_col22_exp = ;
%let tpOutData_col22_input = NTVTP;
%let tpOutData_col22_input_count = 1;
%let tpOutData_col23_name = NTVCD;
%let tpOutData_col23_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col23_length = 3;
%let tpOutData_col23_type = $;
%let tpOutData_col23_format = $3.;
%let tpOutData_col23_informat = $3.;
%let tpOutData_col23_label = %nrquote(NTVCD);
%let tpOutData_col23_input0 = NTVCD;
%let tpOutData_col23_input0_table = CAS.CASIOBOP;
%let tpOutData_col23_exp = ;
%let tpOutData_col23_input = NTVCD;
%let tpOutData_col23_input_count = 1;
%let tpOutData_col24_name = NTVAM;
%let tpOutData_col24_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col24_length = 8;
%let tpOutData_col24_type = ;
%let tpOutData_col24_format = 4.;
%let tpOutData_col24_informat = 4.;
%let tpOutData_col24_label = %nrquote(NTVAM);
%let tpOutData_col24_input0 = NTVAM;
%let tpOutData_col24_input0_table = CAS.CASIOBOP;
%let tpOutData_col24_exp = ;
%let tpOutData_col24_input = NTVAM;
%let tpOutData_col24_input_count = 1;
%let tpOutData_col25_name = NTVTR;
%let tpOutData_col25_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col25_length = 3;
%let tpOutData_col25_type = $;
%let tpOutData_col25_format = $3.;
%let tpOutData_col25_informat = $3.;
%let tpOutData_col25_label = %nrquote(NTVTR);
%let tpOutData_col25_input0 = NTVTR;
%let tpOutData_col25_input0_table = CAS.CASIOBOP;
%let tpOutData_col25_exp = ;
%let tpOutData_col25_input = NTVTR;
%let tpOutData_col25_input_count = 1;
%let tpOutData_col26_name = NTDCD;
%let tpOutData_col26_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col26_length = 3;
%let tpOutData_col26_type = $;
%let tpOutData_col26_format = $3.;
%let tpOutData_col26_informat = $3.;
%let tpOutData_col26_label = %nrquote(NTDCD);
%let tpOutData_col26_input0 = NTDCD;
%let tpOutData_col26_input0_table = CAS.CASIOBOP;
%let tpOutData_col26_exp = ;
%let tpOutData_col26_input = NTDCD;
%let tpOutData_col26_input_count = 1;
%let tpOutData_col27_name = NTDCN;
%let tpOutData_col27_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col27_length = 11;
%let tpOutData_col27_type = $;
%let tpOutData_col27_format = $11.;
%let tpOutData_col27_informat = $11.;
%let tpOutData_col27_label = %nrquote(NTDCN);
%let tpOutData_col27_input0 = NTDCN;
%let tpOutData_col27_input0_table = CAS.CASIOBOP;
%let tpOutData_col27_exp = ;
%let tpOutData_col27_input = NTDCN;
%let tpOutData_col27_input_count = 1;
%let tpOutData_col28_name = NTOAT;
%let tpOutData_col28_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col28_length = 8;
%let tpOutData_col28_type = ;
%let tpOutData_col28_format = 14.;
%let tpOutData_col28_informat = 14.;
%let tpOutData_col28_label = %nrquote(NTOAT);
%let tpOutData_col28_input0 = NTOAT;
%let tpOutData_col28_input0_table = CAS.CASIOBOP;
%let tpOutData_col28_exp = ;
%let tpOutData_col28_input = NTOAT;
%let tpOutData_col28_input_count = 1;
%let tpOutData_col29_name = NTODT;
%let tpOutData_col29_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col29_length = 4;
%let tpOutData_col29_type = $;
%let tpOutData_col29_format = $4.;
%let tpOutData_col29_informat = $4.;
%let tpOutData_col29_label = %nrquote(NTODT);
%let tpOutData_col29_input0 = NTODT;
%let tpOutData_col29_input0_table = CAS.CASIOBOP;
%let tpOutData_col29_exp = ;
%let tpOutData_col29_input = NTODT;
%let tpOutData_col29_input_count = 1;
%let tpOutData_col30_name = NTINC;
%let tpOutData_col30_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col30_length = 1;
%let tpOutData_col30_type = $;
%let tpOutData_col30_format = $1.;
%let tpOutData_col30_informat = $1.;
%let tpOutData_col30_label = %nrquote(NTINC);
%let tpOutData_col30_input0 = NTINC;
%let tpOutData_col30_input0_table = CAS.CASIOBOP;
%let tpOutData_col30_exp = ;
%let tpOutData_col30_input = NTINC;
%let tpOutData_col30_input_count = 1;
%let tpOutData_col31_name = NTNVF;
%let tpOutData_col31_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col31_length = 1;
%let tpOutData_col31_type = $;
%let tpOutData_col31_format = $1.;
%let tpOutData_col31_informat = $1.;
%let tpOutData_col31_label = %nrquote(NTNVF);
%let tpOutData_col31_input0 = NTNVF;
%let tpOutData_col31_input0_table = CAS.CASIOBOP;
%let tpOutData_col31_exp = ;
%let tpOutData_col31_input = NTNVF;
%let tpOutData_col31_input_count = 1;
%let tpOutData_col32_name = NTTHR;
%let tpOutData_col32_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col32_length = 10;
%let tpOutData_col32_type = $;
%let tpOutData_col32_format = $10.;
%let tpOutData_col32_informat = $10.;
%let tpOutData_col32_label = %nrquote(NTTHR);
%let tpOutData_col32_input0 = NTTHR;
%let tpOutData_col32_input0_table = CAS.CASIOBOP;
%let tpOutData_col32_exp = ;
%let tpOutData_col32_input = NTTHR;
%let tpOutData_col32_input_count = 1;
%let tpOutData_col33_name = NTTHD;
%let tpOutData_col33_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col33_length = 8;
%let tpOutData_col33_type = ;
%let tpOutData_col33_format = 6.;
%let tpOutData_col33_informat = 6.;
%let tpOutData_col33_label = %nrquote(NTTHD);
%let tpOutData_col33_input0 = NTTHD;
%let tpOutData_col33_input0_table = CAS.CASIOBOP;
%let tpOutData_col33_exp = ;
%let tpOutData_col33_input = NTTHD;
%let tpOutData_col33_input_count = 1;
%let tpOutData_col34_name = NTCAD;
%let tpOutData_col34_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col34_length = 1;
%let tpOutData_col34_type = $;
%let tpOutData_col34_format = $1.;
%let tpOutData_col34_informat = $1.;
%let tpOutData_col34_label = %nrquote(NTCAD);
%let tpOutData_col34_input0 = NTCAD;
%let tpOutData_col34_input0_table = CAS.CASIOBOP;
%let tpOutData_col34_exp = ;
%let tpOutData_col34_input = NTCAD;
%let tpOutData_col34_input_count = 1;
%let tpOutData_col35_name = NTNAS;
%let tpOutData_col35_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col35_length = 30;
%let tpOutData_col35_type = $;
%let tpOutData_col35_format = $30.;
%let tpOutData_col35_informat = $30.;
%let tpOutData_col35_label = %nrquote(NTNAS);
%let tpOutData_col35_input0 = NTNAS;
%let tpOutData_col35_input0_table = CAS.CASIOBOP;
%let tpOutData_col35_exp = ;
%let tpOutData_col35_input = NTNAS;
%let tpOutData_col35_input_count = 1;
%let tpOutData_col36_name = NTNAM;
%let tpOutData_col36_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col36_length = 30;
%let tpOutData_col36_type = $;
%let tpOutData_col36_format = $30.;
%let tpOutData_col36_informat = $30.;
%let tpOutData_col36_label = %nrquote(NTNAM);
%let tpOutData_col36_input0 = NTNAM;
%let tpOutData_col36_input0_table = CAS.CASIOBOP;
%let tpOutData_col36_exp = ;
%let tpOutData_col36_input = NTNAM;
%let tpOutData_col36_input_count = 1;
%let tpOutData_col37_name = NTNAP;
%let tpOutData_col37_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col37_length = 30;
%let tpOutData_col37_type = $;
%let tpOutData_col37_format = $30.;
%let tpOutData_col37_informat = $30.;
%let tpOutData_col37_label = %nrquote(NTNAP);
%let tpOutData_col37_input0 = NTNAP;
%let tpOutData_col37_input0_table = CAS.CASIOBOP;
%let tpOutData_col37_exp = ;
%let tpOutData_col37_input = NTNAP;
%let tpOutData_col37_input_count = 1;
%let tpOutData_col38_name = NTDTP;
%let tpOutData_col38_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col38_length = 2;
%let tpOutData_col38_type = $;
%let tpOutData_col38_format = $2.;
%let tpOutData_col38_informat = $2.;
%let tpOutData_col38_label = %nrquote(NTDTP);
%let tpOutData_col38_input0 = NTDTP;
%let tpOutData_col38_input0_table = CAS.CASIOBOP;
%let tpOutData_col38_exp = ;
%let tpOutData_col38_input = NTDTP;
%let tpOutData_col38_input_count = 1;
%let tpOutData_col39_name = NTDSR;
%let tpOutData_col39_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col39_length = 10;
%let tpOutData_col39_type = $;
%let tpOutData_col39_format = $10.;
%let tpOutData_col39_informat = $10.;
%let tpOutData_col39_label = %nrquote(NTDSR);
%let tpOutData_col39_input0 = NTDSR;
%let tpOutData_col39_input0_table = CAS.CASIOBOP;
%let tpOutData_col39_exp = ;
%let tpOutData_col39_input = NTDSR;
%let tpOutData_col39_input_count = 1;
%let tpOutData_col40_name = NTDNB;
%let tpOutData_col40_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col40_length = 20;
%let tpOutData_col40_type = $;
%let tpOutData_col40_format = $20.;
%let tpOutData_col40_informat = $20.;
%let tpOutData_col40_label = %nrquote(NTDNB);
%let tpOutData_col40_input0 = NTDNB;
%let tpOutData_col40_input0_table = CAS.CASIOBOP;
%let tpOutData_col40_exp = ;
%let tpOutData_col40_input = NTDNB;
%let tpOutData_col40_input_count = 1;
%let tpOutData_col41_name = NTDDT;
%let tpOutData_col41_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col41_length = 10;
%let tpOutData_col41_type = $;
%let tpOutData_col41_format = $10.;
%let tpOutData_col41_informat = $10.;
%let tpOutData_col41_label = %nrquote(NTDDT);
%let tpOutData_col41_input0 = NTDDT;
%let tpOutData_col41_input0_table = CAS.CASIOBOP;
%let tpOutData_col41_exp = ;
%let tpOutData_col41_input = NTDDT;
%let tpOutData_col41_input_count = 1;
%let tpOutData_col42_name = NTDII;
%let tpOutData_col42_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col42_length = 60;
%let tpOutData_col42_type = $;
%let tpOutData_col42_format = $60.;
%let tpOutData_col42_informat = $60.;
%let tpOutData_col42_label = %nrquote(NTDII);
%let tpOutData_col42_input0 = NTDII;
%let tpOutData_col42_input0_table = CAS.CASIOBOP;
%let tpOutData_col42_exp = ;
%let tpOutData_col42_input = NTDII;
%let tpOutData_col42_input_count = 1;
%let tpOutData_col43_name = NTDDC;
%let tpOutData_col43_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col43_length = 15;
%let tpOutData_col43_type = $;
%let tpOutData_col43_format = $15.;
%let tpOutData_col43_informat = $15.;
%let tpOutData_col43_label = %nrquote(NTDDC);
%let tpOutData_col43_input0 = NTDDC;
%let tpOutData_col43_input0_table = CAS.CASIOBOP;
%let tpOutData_col43_exp = ;
%let tpOutData_col43_input = NTDDC;
%let tpOutData_col43_input_count = 1;
%let tpOutData_col44_name = NTCNT;
%let tpOutData_col44_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col44_length = 2;
%let tpOutData_col44_type = $;
%let tpOutData_col44_format = $2.;
%let tpOutData_col44_informat = $2.;
%let tpOutData_col44_label = %nrquote(NTCNT);
%let tpOutData_col44_input0 = NTCNT;
%let tpOutData_col44_input0_table = CAS.CASIOBOP;
%let tpOutData_col44_exp = ;
%let tpOutData_col44_input = NTCNT;
%let tpOutData_col44_input_count = 1;
%let tpOutData_col45_name = NTUSR1;
%let tpOutData_col45_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col45_length = 10;
%let tpOutData_col45_type = $;
%let tpOutData_col45_format = $10.;
%let tpOutData_col45_informat = $10.;
%let tpOutData_col45_label = %nrquote(NTUSR1);
%let tpOutData_col45_input0 = NTUSR1;
%let tpOutData_col45_input0_table = CAS.CASIOBOP;
%let tpOutData_col45_exp = ;
%let tpOutData_col45_input = NTUSR1;
%let tpOutData_col45_input_count = 1;
%let tpOutData_col46_name = NTUSR2;
%let tpOutData_col46_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col46_length = 10;
%let tpOutData_col46_type = $;
%let tpOutData_col46_format = $10.;
%let tpOutData_col46_informat = $10.;
%let tpOutData_col46_label = %nrquote(NTUSR2);
%let tpOutData_col46_input0 = NTUSR2;
%let tpOutData_col46_input0_table = CAS.CASIOBOP;
%let tpOutData_col46_exp = ;
%let tpOutData_col46_input = NTUSR2;
%let tpOutData_col46_input_count = 1;
%let tpOutData_col47_name = NTUSR3;
%let tpOutData_col47_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col47_length = 10;
%let tpOutData_col47_type = $;
%let tpOutData_col47_format = $10.;
%let tpOutData_col47_informat = $10.;
%let tpOutData_col47_label = %nrquote(NTUSR3);
%let tpOutData_col47_input0 = NTUSR3;
%let tpOutData_col47_input0_table = CAS.CASIOBOP;
%let tpOutData_col47_exp = ;
%let tpOutData_col47_input = NTUSR3;
%let tpOutData_col47_input_count = 1;
%let tpOutData_col48_name = NTUSR4;
%let tpOutData_col48_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col48_length = 10;
%let tpOutData_col48_type = $;
%let tpOutData_col48_format = $10.;
%let tpOutData_col48_informat = $10.;
%let tpOutData_col48_label = %nrquote(NTUSR4);
%let tpOutData_col48_input0 = NTUSR4;
%let tpOutData_col48_input0_table = CAS.CASIOBOP;
%let tpOutData_col48_exp = ;
%let tpOutData_col48_input = NTUSR4;
%let tpOutData_col48_input_count = 1;
%let tpOutData_col49_name = NTTIMI;
%let tpOutData_col49_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col49_length = 8;
%let tpOutData_col49_type = ;
%let tpOutData_col49_format = 7.;
%let tpOutData_col49_informat = 7.;
%let tpOutData_col49_label = %nrquote(NTTIMI);
%let tpOutData_col49_input0 = NTTIMI;
%let tpOutData_col49_input0_table = CAS.CASIOBOP;
%let tpOutData_col49_exp = ;
%let tpOutData_col49_input = NTTIMI;
%let tpOutData_col49_input_count = 1;
%let tpOutData_col50_name = NTTIMA;
%let tpOutData_col50_table = work_stg.CASA_CASIOBOP;
%let tpOutData_col50_length = 8;
%let tpOutData_col50_type = ;
%let tpOutData_col50_format = 7.;
%let tpOutData_col50_informat = 7.;
%let tpOutData_col50_label = %nrquote(NTTIMA);
%let tpOutData_col50_input0 = NTTIMA;
%let tpOutData_col50_input0_table = CAS.CASIOBOP;
%let tpOutData_col50_exp = ;
%let tpOutData_col50_input = NTTIMA;
%let tpOutData_col50_input_count = 1;


proc datasets lib=work_stg nolist nowarn memtype = (data view);
   delete CASA_CASIOBOP;
quit;

%let tpSrcSystem = %nrquote(CAS);
%let tpWhere = ;
%let tpCreateDigest = %nrquote(No);
%let tpResourceId = %nrquote(BY_SOURCE);
%let tpVersion = %nrquote(MIN);

/* List of target columns to keep  */ 
%let _keep = NTBRC NTOTP NTDAT NTTID NTSTS NTTLR NTLTP NTLCD NTBRA NTCNU NTCCY 
        NTACD NTASQ NTPFC NTBOC NTVLD NTNAR NTRAT NTRMF NTRTP NTRST NTDRI 
        NTVTP NTVCD NTVAM NTVTR NTDCD NTDCN NTOAT NTODT NTINC NTNVF NTTHR 
        NTTHD NTCAD NTNAS NTNAM NTNAP NTDTP NTDSR NTDNB NTDDT NTDII NTDDC 
        NTCNT NTUSR1 NTUSR2 NTUSR3 NTUSR4 NTTIMI NTTIMA;
/* List of target columns to keep  */ 
%let keep = NTBRC NTOTP NTDAT NTTID NTSTS NTTLR NTLTP NTLCD NTBRA NTCNU NTCCY 
        NTACD NTASQ NTPFC NTBOC NTVLD NTNAR NTRAT NTRMF NTRTP NTRST NTDRI 
        NTVTP NTVCD NTVAM NTVTR NTDCD NTDCN NTOAT NTODT NTINC NTNVF NTTHR 
        NTTHD NTCAD NTNAS NTNAM NTNAP NTDTP NTDSR NTDNB NTDDT NTDII NTDDC 
        NTCNT NTUSR1 NTUSR2 NTUSR3 NTUSR4 NTTIMI NTTIMA;
/*****************************************************************
*  ВЕРСИЯ:
*     $Id: transform_extract.sas 2953:806283d8673a 2014-05-21 06:26:42Z rusane $
*
******************************************************************
*  НАЗНАЧЕНИЕ:
*     Выгружает набор из источника, рассчитывает MD5-суммы строк.
*     Выгружаются все поля, для которых определен мэппинг.
*
*  ПАРАМЕТРЫ:
*     tpIn                    +  имя входного набора, таблицы из источника
*     tpOutData               +  имя выходного набора, выгруженной таблицы
*     tpOutRegistry           -  имя выходного набора, списка обновляемых записей в реестре
*     tpSrcSystem             +  код источника
*     tpResourceId            +  идентификатор ресурса
*                                По умолчанию BY_SOURCE, т.е. будет определен по входной таблице
*     tpVersion               +  идентификатор версии
*                                По умолчанию MIN, т.е. самая ранняя из доступных
*     tpWhere                 -  условие отбора из входного набора
*     tpCreateDigest          -  создавать (Yes) или нет (No) поле с рассчитанной хэш-суммой (ETL_DIGEST_CD)
*
******************************************************************
*  Ограничения:
*     Если выгрузка обновляет более 1 записи в реестре (зеркальные ресурсы),
*     то все эти ресурсы обязаны иметь одну версию.
*
******************************************************************/

%macro transform_extract;
   /* Если идентификатор ресурса не задан, то все */
   %if %length(&tpResourceId) eq 0 %then %return;
   /* Если идентификатор версии не задан, то все */
   %if %length(&tpVersion) eq 0 %then %return;

   /* Получаем открытые записи реестра */
   %if &_OUTPUT_count le 1 %then %do;
      %local lmvUID tpOutRegistry;
      %unique_id (mpOutKey=lmvUID);
      %let tpOutRegistry       = work.tr_extr_reg_&lmvUID.;
   %end;

   %global ETL_EXTRACT_RC;
   %let ETL_EXTRACT_RC = 0;
   %local lmvVersion;

   %etl_extract_common (
      mpData            =  &tpIn,
      mpResourceId      =  &tpResourceId,
      mpVersion         =  &tpVersion,
      mpOutRegistry     =  &tpOutRegistry,
      mpOutStatusKey    =  ETL_EXTRACT_RC,
      mpOutVersionKey   =  lmvVersion
   );

   %if &ETL_EXTRACT_RC = 1 %then %do;
      /* Выгрузка не производится, если все оригиналы уже выгружены */
      %return;
   %end;
   %if &ETL_EXTRACT_RC = 2 %then
      /* требуется выгрузка */
      %let ETL_EXTRACT_RC = 0;;
   %if &ETL_EXTRACT_RC ne 0 %then %return;

   /* Получаем список полей, для которых определен мэппинг */
   %local lmvInCols;
   %etl_get_input_columns(mpTableMacroName=tpOutData, mpOutKey=lmvInCols);
   %local lmvFieldDigest;
   %if &tpCreateDigest = Yes %then
      %let lmvFieldDigest = ETL_DIGEST_CD;;

   %etl_extract (
      mpIn=&tpIn,
      mpOut=&tpOutData,
      mpWhere=&tpWhere,
      mpKeep=&lmvInCols,
      mpResourceId=-1,
      mpExtractId=&lmvVersion,
      mpSrcSystem="&tpSrcSystem",
      mpFieldDigest=&lmvFieldDigest,
      mpFieldSrcSystem=SOURCE_SYSTEM_CD,
      mpFieldExtractId=ETL_EXTRACT_ID,
      mpFieldResourceId=ETL_RESOURCE_ID,
      mpIn_engine=&tpIn_engine
   );
%mend transform_extract;

%transform_extract;


%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end Выгрузка данных **/

/*==========================================================================* 
 * Step:            Разместить выгрузку в архиве          A52HJCF1.AT0025EN * 
 * Transform:       Разместить выгрузку в архиве                            * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    CASA_CASIOBOP -                       A52HJCF1.AH0002JO * 
 *                   work_stg.CASA_CASIOBOP                                 * 
 * Target Table:    CASA_CASIOBOP_ARCH -                  A52HJCF1.AH0000E7 * 
 *                   etl_stg.CASA_CASIOBOP_ARCH                             * 
 *==========================================================================*/ 

%let transformID = %quote(A52HJCF1.AT0025EN);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

/* Access the data for ETL_STG  */ 
LIBNAME etl_stg ORACLE  DEFER=YES  PATH="DWH04.IMB.RU"  SCHEMA=ETL_STG  AUTHDOMAIN="OraAuth_ETL_STG_DWH04_T" ;
%rcSet(&syslibrc); 

%let SYSLAST = %nrquote(work_stg.CASA_CASIOBOP); 

%let _INPUT_count = 1; 
%let _INPUT = work_stg.CASA_CASIOBOP;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/DWH_DWHDDS_STG/Tables/WORK_STG/CAS/CASA_CASIOBOP%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let tpInData = work_stg.CASA_CASIOBOP;
%let tpInData_connect = null;
%let tpInData_engine = BASE;
%let tpInData_memtype = DATA;
%let tpInData_options = %nrquote();
%let tpInData_alter = %nrquote();
%let tpInData_path = %nrquote(/DWH_DWHDDS_STG/Tables/WORK_STG/CAS/CASA_CASIOBOP%(Table%));
%let tpInData_type = 1;
%let tpInData_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = etl_stg.CASA_CASIOBOP_ARCH;
%let _OUTPUT_connect =  DEFER=YES PATH="DWH04.IMB.RU" AUTHDOMAIN="OraAuth_ETL_STG_DWH04_T" 
;
%let _OUTPUT_engine = ORACLE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/DWH_DWHDDS_STG/Tables/ETL_STG/CAS/CASA_CASIOBOP_ARCH%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = NTBRC NTOTP NTDAT NTTID NTSTS NTTLR NTLTP NTLCD NTBRA NTCNU NTCCY 
        NTACD NTASQ NTPFC NTBOC NTVLD NTNAR NTRAT NTRMF NTRTP NTRST NTDRI 
        NTVTP NTVCD NTVAM NTVTR NTDCD NTDCN NTOAT NTODT NTINC NTNVF NTTHR 
        NTTHD NTCAD NTNAS NTNAM NTNAP NTDTP NTDSR NTDNB NTDDT NTDII NTDDC 
        NTCNT NTUSR1 NTUSR2 NTUSR3 NTUSR4 NTTIMI NTTIMA ETL_EXTRACT_ID 
        ETL_RESOURCE_ID SOURCE_SYSTEM_CD;

%let tpOut = etl_stg.CASA_CASIOBOP_ARCH;
%let tpOut_connect =  DEFER=YES PATH="DWH04.IMB.RU" AUTHDOMAIN="OraAuth_ETL_STG_DWH04_T" 
;
%let tpOut_engine = ORACLE;
%let tpOut_memtype = DATA;
%let tpOut_options = %nrquote();
%let tpOut_alter = %nrquote();
%let tpOut_path = %nrquote(/DWH_DWHDDS_STG/Tables/ETL_STG/CAS/CASA_CASIOBOP_ARCH%(Table%));
%let tpOut_type = 1;
%let tpOut_label = %nrquote();
/* List of target columns to keep  */ 
%let tpOut_keep = NTBRC NTOTP NTDAT NTTID NTSTS NTTLR NTLTP NTLCD NTBRA NTCNU NTCCY 
        NTACD NTASQ NTPFC NTBOC NTVLD NTNAR NTRAT NTRMF NTRTP NTRST NTDRI 
        NTVTP NTVCD NTVAM NTVTR NTDCD NTDCN NTOAT NTODT NTINC NTNVF NTTHR 
        NTTHD NTCAD NTNAS NTNAM NTNAP NTDTP NTDSR NTDNB NTDDT NTDII NTDDC 
        NTCNT NTUSR1 NTUSR2 NTUSR3 NTUSR4 NTTIMI NTTIMA ETL_EXTRACT_ID 
        ETL_RESOURCE_ID SOURCE_SYSTEM_CD;



/* List of target columns to keep  */ 
%let _keep = NTBRC NTOTP NTDAT NTTID NTSTS NTTLR NTLTP NTLCD NTBRA NTCNU NTCCY 
        NTACD NTASQ NTPFC NTBOC NTVLD NTNAR NTRAT NTRMF NTRTP NTRST NTDRI 
        NTVTP NTVCD NTVAM NTVTR NTDCD NTDCN NTOAT NTODT NTINC NTNVF NTTHR 
        NTTHD NTCAD NTNAS NTNAM NTNAP NTDTP NTDSR NTDNB NTDDT NTDII NTDDC 
        NTCNT NTUSR1 NTUSR2 NTUSR3 NTUSR4 NTTIMI NTTIMA ETL_EXTRACT_ID 
        ETL_RESOURCE_ID SOURCE_SYSTEM_CD;
/* List of target columns to keep  */ 
%let keep = NTBRC NTOTP NTDAT NTTID NTSTS NTTLR NTLTP NTLCD NTBRA NTCNU NTCCY 
        NTACD NTASQ NTPFC NTBOC NTVLD NTNAR NTRAT NTRMF NTRTP NTRST NTDRI 
        NTVTP NTVCD NTVAM NTVTR NTDCD NTDCN NTOAT NTODT NTINC NTNVF NTTHR 
        NTTHD NTCAD NTNAS NTNAM NTNAP NTDTP NTDSR NTDNB NTDDT NTDII NTDDC 
        NTCNT NTUSR1 NTUSR2 NTUSR3 NTUSR4 NTTIMI NTTIMA ETL_EXTRACT_ID 
        ETL_RESOURCE_ID SOURCE_SYSTEM_CD;
/*****************************************************************
*  ВЕРСИЯ:
*     $Id: transform_archive_put.sas 2517:eb3f59b6fe1d 2013-11-15 11:46:40Z rusane $
*
******************************************************************
*  НАЗНАЧЕНИЕ:
*     Размещает выгруженный набор в архиве, регистрирует выгрузку в реестре.
*
*  ПАРАМЕТРЫ:
*     tpInData             +  имя входного набора, выгруженной таблицы
*     tpInRegistry         -  имя входного набора, списка обновляемых записей в реестре
*                             Если не задан, то будет определен по архивной таблице
*     tpOut                +  имя выходного набора, архивной таблицы
*
******************************************************************/

%macro transform_archive_put;
   %etl_archive_put (
      mpInData                =  &tpInData,
      mpInRegistry            =
                                 %if &_INPUT_count ge 2 %then %do;
                                    &tpInRegistry
                                 %end;
                                 ,
      mpOut                   =  &tpOut
   );
%mend transform_archive_put;

%transform_archive_put;


%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end Разместить выгрузку в архиве **/

/*==========================================================================* 
 * Step:            Завершить модуль                      A52HJCF1.AT0025EO * 
 * Transform:       Завершить модуль                                        * 
 * Description:                                                             * 
 *==========================================================================*/ 

%let transformID = %quote(A52HJCF1.AT0025EO);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


/*****************************************************************
* ВЕРСИЯ:
*   $Id: transform_job_finish.sas 4063:34040bca471f 2015-06-19 09:28:58Z rusane $
*
******************************************************************
* НАЗНАЧЕНИЕ:
*   Регистрирует конец модуля ETL.
*
* ПАРАМЕТРЫ:
*   нет
*
******************************************************************/

%macro transform_job_finish;
   %etl_job_finish;
%mend transform_job_finish;

%transform_job_finish;


%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end Завершить модуль **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

