/**************************************************************************** 
 * Job:             101_16_92_Extract_Mis_VDMTB_MONTH     A52HJCF1.AR00009B * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: sasmeta4.dwhgridtest.imb.ru                             * 
 * Port:            8564                                                    * 
 * Location:        /DWH_DWHDDS_STG/Jobs/101_Extract/101_16_MIS/Includes/   * 
 *                  Non-TDA                                                 * 
 *                                                                          * 
 * Server:          SASApp                                A5H5E9KJ.AS000002 * 
 *                                                                          * 
 * Source Tables:   vdmtb_Month - MIS.vdmtb_Month         A52HJCF1.AH000271 * 
 *                  VDMTB_MONTH - work_stg.VDMTB_MONTH    A52HJCF1.AH0003FE * 
 * Target Tables:   VDMTB_MONTH - work_stg.VDMTB_MONTH    A52HJCF1.AH0003FE * 
 *                  VDMTB_MONTH_ARCH -                    A52HJCF1.AH0001C2 * 
 *                   etl_stg.VDMTB_MONTH_ARCH                               * 
 *                                                                          * 
 * Generated on:    18 апреля 2022 г. 20:56:54 MSK                          * 
 * Generated by:    er35863@dmz.imb.ru                                      * 
 * Version:         SAS Data Integration Studio 4.904                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A52HJCF1.AR00009B);
%let etls_jobName = %nrquote(101_16_92_Extract_Mis_VDMTB_MONTH);
%let etls_userID = %nrquote(er35863@dmz.imb.ru);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */ 
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            Начать модуль                         A52HJCF1.AT0020PN * 
 * Transform:       Начать модуль                                           * 
 * Description:                                                             * 
 *==========================================================================*/ 

%let transformID = %quote(A52HJCF1.AT0020PN);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


/*****************************************************************
*  ВЕРСИЯ:
*     $Id: transform_job_start.sas 4060:d0a33a5b822b 2015-06-19 09:27:21Z rusane $
*
******************************************************************
*  НАЗНАЧЕНИЕ:
*     Регистрирует начало модуля ETL.
*
*  ПАРАМЕТРЫ:
*     нет
*
******************************************************************/

%macro transform_job_start;
   %etl_job_start;
%mend transform_job_start;

%transform_job_start;


%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end Начать модуль **/

/*==========================================================================* 
 * Step:            Выгрузка данных                       A52HJCF1.AT0020PO * 
 * Transform:       Выгрузка данных                                         * 
 * Description:     Выгружает набор из источника, рассчитывает MD5-суммы    * 
 *                   строк.                                                 * 
 *                                                                          * 
 * Source Table:    vdmtb_Month - MIS.vdmtb_Month         A52HJCF1.AH000271 * 
 * Target Table:    VDMTB_MONTH - work_stg.VDMTB_MONTH    A52HJCF1.AH0003FE * 
 *==========================================================================*/ 

%let transformID = %quote(A52HJCF1.AT0020PO);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

/* Access the data for MIS  */ 
LIBNAME MIS SQLSVR  DEFER=YES  READBUFF=1600  Datasrc=MIS_REVENUE_VS749  SCHEMA=dbo  AUTHDOMAIN="MSAuth_mis2dwh_rs_dev_mis_dwh_T" ;
%rcSet(&syslibrc); 

/* Access the data for WORK_STG  */ 
LIBNAME work_stg BASE "!ETL_DATA_ROOT/work_stg";
%rcSet(&syslibrc); 

%let SYSLAST = %nrquote(MIS.vdmtb_Month); 

%let _INPUT_count = 1; 
%let _INPUT = MIS.vdmtb_Month;
%let _INPUT_connect =  DEFER=YES READBUFF=1600 DATASRC=MIS_REVENUE_VS749 AUTHDOMAIN="MSAuth_mis2dwh_rs_dev_mis_dwh_T" 
;
%let _INPUT_engine = SQLSVR;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/DWH_DWHDDS_STG/Tables/MIS/vdmtb_Month%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let tpIn = MIS.vdmtb_Month;
%let tpIn_connect =  DEFER=YES READBUFF=1600 DATASRC=MIS_REVENUE_VS749 AUTHDOMAIN="MSAuth_mis2dwh_rs_dev_mis_dwh_T" 
;
%let tpIn_engine = SQLSVR;
%let tpIn_memtype = VIEW;
%let tpIn_options = %nrquote();
%let tpIn_alter = %nrquote();
%let tpIn_path = %nrquote(/DWH_DWHDDS_STG/Tables/MIS/vdmtb_Month%(Table%));
%let tpIn_type = 1;
%let tpIn_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work_stg.VDMTB_MONTH;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/DWH_DWHDDS_STG/Tables/WORK_STG/MIS/VDMTB_MONTH%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = month_nbr month_name qrtr_nbr half_year_nbr year_nbr month_len 
        month_ID step_evt_id ETL_EXTRACT_ID ETL_RESOURCE_ID ETL_DIGEST_CD 
        SOURCE_SYSTEM_CD;
%let _OUTPUT_col_count = 12;
%let _OUTPUT_col0_name = month_nbr;
%let _OUTPUT_col0_table = work_stg.VDMTB_MONTH;
%let _OUTPUT_col0_length = 8;
%let _OUTPUT_col0_type = ;
%let _OUTPUT_col0_format = 11.;
%let _OUTPUT_col0_informat = 11.;
%let _OUTPUT_col0_label = %nrquote(month_nbr);
%let _OUTPUT_col0_input0 = month_nbr;
%let _OUTPUT_col0_input0_table = MIS.vdmtb_Month;
%let _OUTPUT_col0_exp = ;
%let _OUTPUT_col0_input = month_nbr;
%let _OUTPUT_col0_input_count = 1;
%let _OUTPUT_col1_name = month_name;
%let _OUTPUT_col1_table = work_stg.VDMTB_MONTH;
%let _OUTPUT_col1_length = 10;
%let _OUTPUT_col1_type = $;
%let _OUTPUT_col1_format = $10.;
%let _OUTPUT_col1_informat = $10.;
%let _OUTPUT_col1_label = %nrquote(month_name);
%let _OUTPUT_col1_input0 = month_name;
%let _OUTPUT_col1_input0_table = MIS.vdmtb_Month;
%let _OUTPUT_col1_exp = ;
%let _OUTPUT_col1_input = month_name;
%let _OUTPUT_col1_input_count = 1;
%let _OUTPUT_col2_name = qrtr_nbr;
%let _OUTPUT_col2_table = work_stg.VDMTB_MONTH;
%let _OUTPUT_col2_length = 8;
%let _OUTPUT_col2_type = ;
%let _OUTPUT_col2_format = 11.;
%let _OUTPUT_col2_informat = 11.;
%let _OUTPUT_col2_label = %nrquote(qrtr_nbr);
%let _OUTPUT_col2_input0 = qrtr_nbr;
%let _OUTPUT_col2_input0_table = MIS.vdmtb_Month;
%let _OUTPUT_col2_exp = ;
%let _OUTPUT_col2_input = qrtr_nbr;
%let _OUTPUT_col2_input_count = 1;
%let _OUTPUT_col3_name = half_year_nbr;
%let _OUTPUT_col3_table = work_stg.VDMTB_MONTH;
%let _OUTPUT_col3_length = 8;
%let _OUTPUT_col3_type = ;
%let _OUTPUT_col3_format = 11.;
%let _OUTPUT_col3_informat = 11.;
%let _OUTPUT_col3_label = %nrquote(half_year_nbr);
%let _OUTPUT_col3_input0 = half_year_nbr;
%let _OUTPUT_col3_input0_table = MIS.vdmtb_Month;
%let _OUTPUT_col3_exp = ;
%let _OUTPUT_col3_input = half_year_nbr;
%let _OUTPUT_col3_input_count = 1;
%let _OUTPUT_col4_name = year_nbr;
%let _OUTPUT_col4_table = work_stg.VDMTB_MONTH;
%let _OUTPUT_col4_length = 8;
%let _OUTPUT_col4_type = ;
%let _OUTPUT_col4_format = 11.;
%let _OUTPUT_col4_informat = 11.;
%let _OUTPUT_col4_label = %nrquote(year_nbr);
%let _OUTPUT_col4_input0 = year_nbr;
%let _OUTPUT_col4_input0_table = MIS.vdmtb_Month;
%let _OUTPUT_col4_exp = ;
%let _OUTPUT_col4_input = year_nbr;
%let _OUTPUT_col4_input_count = 1;
%let _OUTPUT_col5_name = month_len;
%let _OUTPUT_col5_table = work_stg.VDMTB_MONTH;
%let _OUTPUT_col5_length = 8;
%let _OUTPUT_col5_type = ;
%let _OUTPUT_col5_format = 11.;
%let _OUTPUT_col5_informat = 11.;
%let _OUTPUT_col5_label = %nrquote(month_len);
%let _OUTPUT_col5_input0 = month_len;
%let _OUTPUT_col5_input0_table = MIS.vdmtb_Month;
%let _OUTPUT_col5_exp = ;
%let _OUTPUT_col5_input = month_len;
%let _OUTPUT_col5_input_count = 1;
%let _OUTPUT_col6_name = month_ID;
%let _OUTPUT_col6_table = work_stg.VDMTB_MONTH;
%let _OUTPUT_col6_length = 8;
%let _OUTPUT_col6_type = ;
%let _OUTPUT_col6_format = 11.;
%let _OUTPUT_col6_informat = 11.;
%let _OUTPUT_col6_label = %nrquote(month_ID);
%let _OUTPUT_col6_input0 = month_ID;
%let _OUTPUT_col6_input0_table = MIS.vdmtb_Month;
%let _OUTPUT_col6_exp = ;
%let _OUTPUT_col6_input = month_ID;
%let _OUTPUT_col6_input_count = 1;
%let _OUTPUT_col7_name = step_evt_id;
%let _OUTPUT_col7_table = work_stg.VDMTB_MONTH;
%let _OUTPUT_col7_length = 8;
%let _OUTPUT_col7_type = ;
%let _OUTPUT_col7_format = 32.;
%let _OUTPUT_col7_informat = 32.;
%let _OUTPUT_col7_label = %nrquote(step_evt_id);
%let _OUTPUT_col7_input0 = step_evt_id;
%let _OUTPUT_col7_input0_table = MIS.vdmtb_Month;
%let _OUTPUT_col7_exp = ;
%let _OUTPUT_col7_input = step_evt_id;
%let _OUTPUT_col7_input_count = 1;
%let _OUTPUT_col8_name = ETL_EXTRACT_ID;
%let _OUTPUT_col8_table = work_stg.VDMTB_MONTH;
%let _OUTPUT_col8_length = 8;
%let _OUTPUT_col8_type = ;
%let _OUTPUT_col8_format = BEST.;
%let _OUTPUT_col8_informat = ;
%let _OUTPUT_col8_label = %nrquote(ETL_EXTRACT_ID);
%let _OUTPUT_col8_exp = ;
%let _OUTPUT_col8_input_count = 0;
%let _OUTPUT_col9_name = ETL_RESOURCE_ID;
%let _OUTPUT_col9_table = work_stg.VDMTB_MONTH;
%let _OUTPUT_col9_length = 8;
%let _OUTPUT_col9_type = ;
%let _OUTPUT_col9_format = 21.;
%let _OUTPUT_col9_informat = 21.;
%let _OUTPUT_col9_label = %nrquote(ETL_RESOURCE_ID);
%let _OUTPUT_col9_exp = ;
%let _OUTPUT_col9_input_count = 0;
%let _OUTPUT_col10_name = ETL_DIGEST_CD;
%let _OUTPUT_col10_table = work_stg.VDMTB_MONTH;
%let _OUTPUT_col10_length = 16;
%let _OUTPUT_col10_type = $;
%let _OUTPUT_col10_format = $HEX32.;
%let _OUTPUT_col10_informat = ;
%let _OUTPUT_col10_label = %nrquote(ETL_DIGEST_CD);
%let _OUTPUT_col10_exp = ;
%let _OUTPUT_col10_input_count = 0;
%let _OUTPUT_col11_name = SOURCE_SYSTEM_CD;
%let _OUTPUT_col11_table = work_stg.VDMTB_MONTH;
%let _OUTPUT_col11_length = 3;
%let _OUTPUT_col11_type = $;
%let _OUTPUT_col11_format = $3.;
%let _OUTPUT_col11_informat = ;
%let _OUTPUT_col11_label = %nrquote(SOURCE_SYSTEM_CD);
%let _OUTPUT_col11_exp = ;
%let _OUTPUT_col11_input_count = 0;

%let tpOutData = work_stg.VDMTB_MONTH;
%let tpOutData_connect = null;
%let tpOutData_engine = BASE;
%let tpOutData_memtype = DATA;
%let tpOutData_options = %nrquote();
%let tpOutData_alter = %nrquote();
%let tpOutData_path = %nrquote(/DWH_DWHDDS_STG/Tables/WORK_STG/MIS/VDMTB_MONTH%(Table%));
%let tpOutData_type = 1;
%let tpOutData_label = %nrquote();
/* List of target columns to keep  */ 
%let tpOutData_keep = month_nbr month_name qrtr_nbr half_year_nbr year_nbr month_len 
        month_ID step_evt_id ETL_EXTRACT_ID ETL_RESOURCE_ID ETL_DIGEST_CD 
        SOURCE_SYSTEM_CD;
%let tpOutData_col_count = 12;
%let tpOutData_col0_name = month_nbr;
%let tpOutData_col0_table = work_stg.VDMTB_MONTH;
%let tpOutData_col0_length = 8;
%let tpOutData_col0_type = ;
%let tpOutData_col0_format = 11.;
%let tpOutData_col0_informat = 11.;
%let tpOutData_col0_label = %nrquote(month_nbr);
%let tpOutData_col0_input0 = month_nbr;
%let tpOutData_col0_input0_table = MIS.vdmtb_Month;
%let tpOutData_col0_exp = ;
%let tpOutData_col0_input = month_nbr;
%let tpOutData_col0_input_count = 1;
%let tpOutData_col1_name = month_name;
%let tpOutData_col1_table = work_stg.VDMTB_MONTH;
%let tpOutData_col1_length = 10;
%let tpOutData_col1_type = $;
%let tpOutData_col1_format = $10.;
%let tpOutData_col1_informat = $10.;
%let tpOutData_col1_label = %nrquote(month_name);
%let tpOutData_col1_input0 = month_name;
%let tpOutData_col1_input0_table = MIS.vdmtb_Month;
%let tpOutData_col1_exp = ;
%let tpOutData_col1_input = month_name;
%let tpOutData_col1_input_count = 1;
%let tpOutData_col2_name = qrtr_nbr;
%let tpOutData_col2_table = work_stg.VDMTB_MONTH;
%let tpOutData_col2_length = 8;
%let tpOutData_col2_type = ;
%let tpOutData_col2_format = 11.;
%let tpOutData_col2_informat = 11.;
%let tpOutData_col2_label = %nrquote(qrtr_nbr);
%let tpOutData_col2_input0 = qrtr_nbr;
%let tpOutData_col2_input0_table = MIS.vdmtb_Month;
%let tpOutData_col2_exp = ;
%let tpOutData_col2_input = qrtr_nbr;
%let tpOutData_col2_input_count = 1;
%let tpOutData_col3_name = half_year_nbr;
%let tpOutData_col3_table = work_stg.VDMTB_MONTH;
%let tpOutData_col3_length = 8;
%let tpOutData_col3_type = ;
%let tpOutData_col3_format = 11.;
%let tpOutData_col3_informat = 11.;
%let tpOutData_col3_label = %nrquote(half_year_nbr);
%let tpOutData_col3_input0 = half_year_nbr;
%let tpOutData_col3_input0_table = MIS.vdmtb_Month;
%let tpOutData_col3_exp = ;
%let tpOutData_col3_input = half_year_nbr;
%let tpOutData_col3_input_count = 1;
%let tpOutData_col4_name = year_nbr;
%let tpOutData_col4_table = work_stg.VDMTB_MONTH;
%let tpOutData_col4_length = 8;
%let tpOutData_col4_type = ;
%let tpOutData_col4_format = 11.;
%let tpOutData_col4_informat = 11.;
%let tpOutData_col4_label = %nrquote(year_nbr);
%let tpOutData_col4_input0 = year_nbr;
%let tpOutData_col4_input0_table = MIS.vdmtb_Month;
%let tpOutData_col4_exp = ;
%let tpOutData_col4_input = year_nbr;
%let tpOutData_col4_input_count = 1;
%let tpOutData_col5_name = month_len;
%let tpOutData_col5_table = work_stg.VDMTB_MONTH;
%let tpOutData_col5_length = 8;
%let tpOutData_col5_type = ;
%let tpOutData_col5_format = 11.;
%let tpOutData_col5_informat = 11.;
%let tpOutData_col5_label = %nrquote(month_len);
%let tpOutData_col5_input0 = month_len;
%let tpOutData_col5_input0_table = MIS.vdmtb_Month;
%let tpOutData_col5_exp = ;
%let tpOutData_col5_input = month_len;
%let tpOutData_col5_input_count = 1;
%let tpOutData_col6_name = month_ID;
%let tpOutData_col6_table = work_stg.VDMTB_MONTH;
%let tpOutData_col6_length = 8;
%let tpOutData_col6_type = ;
%let tpOutData_col6_format = 11.;
%let tpOutData_col6_informat = 11.;
%let tpOutData_col6_label = %nrquote(month_ID);
%let tpOutData_col6_input0 = month_ID;
%let tpOutData_col6_input0_table = MIS.vdmtb_Month;
%let tpOutData_col6_exp = ;
%let tpOutData_col6_input = month_ID;
%let tpOutData_col6_input_count = 1;
%let tpOutData_col7_name = step_evt_id;
%let tpOutData_col7_table = work_stg.VDMTB_MONTH;
%let tpOutData_col7_length = 8;
%let tpOutData_col7_type = ;
%let tpOutData_col7_format = 32.;
%let tpOutData_col7_informat = 32.;
%let tpOutData_col7_label = %nrquote(step_evt_id);
%let tpOutData_col7_input0 = step_evt_id;
%let tpOutData_col7_input0_table = MIS.vdmtb_Month;
%let tpOutData_col7_exp = ;
%let tpOutData_col7_input = step_evt_id;
%let tpOutData_col7_input_count = 1;
%let tpOutData_col8_name = ETL_EXTRACT_ID;
%let tpOutData_col8_table = work_stg.VDMTB_MONTH;
%let tpOutData_col8_length = 8;
%let tpOutData_col8_type = ;
%let tpOutData_col8_format = BEST.;
%let tpOutData_col8_informat = ;
%let tpOutData_col8_label = %nrquote(ETL_EXTRACT_ID);
%let tpOutData_col8_exp = ;
%let tpOutData_col8_input_count = 0;
%let tpOutData_col9_name = ETL_RESOURCE_ID;
%let tpOutData_col9_table = work_stg.VDMTB_MONTH;
%let tpOutData_col9_length = 8;
%let tpOutData_col9_type = ;
%let tpOutData_col9_format = 21.;
%let tpOutData_col9_informat = 21.;
%let tpOutData_col9_label = %nrquote(ETL_RESOURCE_ID);
%let tpOutData_col9_exp = ;
%let tpOutData_col9_input_count = 0;
%let tpOutData_col10_name = ETL_DIGEST_CD;
%let tpOutData_col10_table = work_stg.VDMTB_MONTH;
%let tpOutData_col10_length = 16;
%let tpOutData_col10_type = $;
%let tpOutData_col10_format = $HEX32.;
%let tpOutData_col10_informat = ;
%let tpOutData_col10_label = %nrquote(ETL_DIGEST_CD);
%let tpOutData_col10_exp = ;
%let tpOutData_col10_input_count = 0;
%let tpOutData_col11_name = SOURCE_SYSTEM_CD;
%let tpOutData_col11_table = work_stg.VDMTB_MONTH;
%let tpOutData_col11_length = 3;
%let tpOutData_col11_type = $;
%let tpOutData_col11_format = $3.;
%let tpOutData_col11_informat = ;
%let tpOutData_col11_label = %nrquote(SOURCE_SYSTEM_CD);
%let tpOutData_col11_exp = ;
%let tpOutData_col11_input_count = 0;


proc datasets lib=work_stg nolist nowarn memtype = (data view);
   delete VDMTB_MONTH;
quit;

%let tpSrcSystem = %nrquote(MIS);
%let tpWhere = ;
%let tpCreateDigest = %nrquote(Yes);
%let tpResourceId = %nrquote(BY_SOURCE);
%let tpVersion = %nrquote(MIN);

/* List of target columns to keep  */ 
%let _keep = month_nbr month_name qrtr_nbr half_year_nbr year_nbr month_len 
        month_ID step_evt_id ETL_EXTRACT_ID ETL_RESOURCE_ID ETL_DIGEST_CD 
        SOURCE_SYSTEM_CD;
/* List of target columns to keep  */ 
%let keep = month_nbr month_name qrtr_nbr half_year_nbr year_nbr month_len 
        month_ID step_evt_id ETL_EXTRACT_ID ETL_RESOURCE_ID ETL_DIGEST_CD 
        SOURCE_SYSTEM_CD;
/*****************************************************************
*  ВЕРСИЯ:
*     $Id: transform_extract.sas 2953:806283d8673a 2014-05-21 06:26:42Z rusane $
*
******************************************************************
*  НАЗНАЧЕНИЕ:
*     Выгружает набор из источника, рассчитывает MD5-суммы строк.
*     Выгружаются все поля, для которых определен мэппинг.
*
*  ПАРАМЕТРЫ:
*     tpIn                    +  имя входного набора, таблицы из источника
*     tpOutData               +  имя выходного набора, выгруженной таблицы
*     tpOutRegistry           -  имя выходного набора, списка обновляемых записей в реестре
*     tpSrcSystem             +  код источника
*     tpResourceId            +  идентификатор ресурса
*                                По умолчанию BY_SOURCE, т.е. будет определен по входной таблице
*     tpVersion               +  идентификатор версии
*                                По умолчанию MIN, т.е. самая ранняя из доступных
*     tpWhere                 -  условие отбора из входного набора
*     tpCreateDigest          -  создавать (Yes) или нет (No) поле с рассчитанной хэш-суммой (ETL_DIGEST_CD)
*
******************************************************************
*  Ограничения:
*     Если выгрузка обновляет более 1 записи в реестре (зеркальные ресурсы),
*     то все эти ресурсы обязаны иметь одну версию.
*
******************************************************************/

%macro transform_extract;
   /* Если идентификатор ресурса не задан, то все */
   %if %length(&tpResourceId) eq 0 %then %return;
   /* Если идентификатор версии не задан, то все */
   %if %length(&tpVersion) eq 0 %then %return;

   /* Получаем открытые записи реестра */
   %if &_OUTPUT_count le 1 %then %do;
      %local lmvUID tpOutRegistry;
      %unique_id (mpOutKey=lmvUID);
      %let tpOutRegistry       = work.tr_extr_reg_&lmvUID.;
   %end;

   %global ETL_EXTRACT_RC;
   %let ETL_EXTRACT_RC = 0;
   %local lmvVersion;

   %etl_extract_common (
      mpData            =  &tpIn,
      mpResourceId      =  &tpResourceId,
      mpVersion         =  &tpVersion,
      mpOutRegistry     =  &tpOutRegistry,
      mpOutStatusKey    =  ETL_EXTRACT_RC,
      mpOutVersionKey   =  lmvVersion
   );

   %if &ETL_EXTRACT_RC = 1 %then %do;
      /* Выгрузка не производится, если все оригиналы уже выгружены */
      %return;
   %end;
   %if &ETL_EXTRACT_RC = 2 %then
      /* требуется выгрузка */
      %let ETL_EXTRACT_RC = 0;;
   %if &ETL_EXTRACT_RC ne 0 %then %return;

   /* Получаем список полей, для которых определен мэппинг */
   %local lmvInCols;
   %etl_get_input_columns(mpTableMacroName=tpOutData, mpOutKey=lmvInCols);
   %local lmvFieldDigest;
   %if &tpCreateDigest = Yes %then
      %let lmvFieldDigest = ETL_DIGEST_CD;;

   %etl_extract (
      mpIn=&tpIn,
      mpOut=&tpOutData,
      mpWhere=&tpWhere,
      mpKeep=&lmvInCols,
      mpResourceId=-1,
      mpExtractId=&lmvVersion,
      mpSrcSystem="&tpSrcSystem",
      mpFieldDigest=&lmvFieldDigest,
      mpFieldSrcSystem=SOURCE_SYSTEM_CD,
      mpFieldExtractId=ETL_EXTRACT_ID,
      mpFieldResourceId=ETL_RESOURCE_ID,
      mpIn_engine=&tpIn_engine
   );
%mend transform_extract;

%transform_extract;


%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end Выгрузка данных **/

/*==========================================================================* 
 * Step:            Разместить выгрузку в архиве          A52HJCF1.AT0020PP * 
 * Transform:       Разместить выгрузку в архиве                            * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    VDMTB_MONTH - work_stg.VDMTB_MONTH    A52HJCF1.AH0003FE * 
 * Target Table:    VDMTB_MONTH_ARCH -                    A52HJCF1.AH0001C2 * 
 *                   etl_stg.VDMTB_MONTH_ARCH                               * 
 *==========================================================================*/ 

%let transformID = %quote(A52HJCF1.AT0020PP);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

/* Access the data for ETL_STG  */ 
LIBNAME etl_stg ORACLE  DEFER=YES  PATH="DWH04.IMB.RU"  SCHEMA=ETL_STG  AUTHDOMAIN="OraAuth_ETL_STG_DWH04_T" ;
%rcSet(&syslibrc); 

%let SYSLAST = %nrquote(work_stg.VDMTB_MONTH); 

%let _INPUT_count = 1; 
%let _INPUT = work_stg.VDMTB_MONTH;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/DWH_DWHDDS_STG/Tables/WORK_STG/MIS/VDMTB_MONTH%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let tpInData = work_stg.VDMTB_MONTH;
%let tpInData_connect = null;
%let tpInData_engine = BASE;
%let tpInData_memtype = DATA;
%let tpInData_options = %nrquote();
%let tpInData_alter = %nrquote();
%let tpInData_path = %nrquote(/DWH_DWHDDS_STG/Tables/WORK_STG/MIS/VDMTB_MONTH%(Table%));
%let tpInData_type = 1;
%let tpInData_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = etl_stg.VDMTB_MONTH_ARCH;
%let _OUTPUT_connect =  DEFER=YES PATH="DWH04.IMB.RU" AUTHDOMAIN="OraAuth_ETL_STG_DWH04_T" 
;
%let _OUTPUT_engine = ORACLE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/DWH_DWHDDS_STG/Tables/ETL_STG/MIS/VDMTB_MONTH_ARCH%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = MONTH_NBR MONTH_NAME QRTR_NBR HALF_YEAR_NBR YEAR_NBR MONTH_LEN 
        MONTH_ID STEP_EVT_ID ETL_EXTRACT_ID ETL_RESOURCE_ID ETL_DIGEST_CD 
        SOURCE_SYSTEM_CD;

%let tpOut = etl_stg.VDMTB_MONTH_ARCH;
%let tpOut_connect =  DEFER=YES PATH="DWH04.IMB.RU" AUTHDOMAIN="OraAuth_ETL_STG_DWH04_T" 
;
%let tpOut_engine = ORACLE;
%let tpOut_memtype = DATA;
%let tpOut_options = %nrquote();
%let tpOut_alter = %nrquote();
%let tpOut_path = %nrquote(/DWH_DWHDDS_STG/Tables/ETL_STG/MIS/VDMTB_MONTH_ARCH%(Table%));
%let tpOut_type = 1;
%let tpOut_label = %nrquote();
/* List of target columns to keep  */ 
%let tpOut_keep = MONTH_NBR MONTH_NAME QRTR_NBR HALF_YEAR_NBR YEAR_NBR MONTH_LEN 
        MONTH_ID STEP_EVT_ID ETL_EXTRACT_ID ETL_RESOURCE_ID ETL_DIGEST_CD 
        SOURCE_SYSTEM_CD;



/* List of target columns to keep  */ 
%let _keep = MONTH_NBR MONTH_NAME QRTR_NBR HALF_YEAR_NBR YEAR_NBR MONTH_LEN 
        MONTH_ID STEP_EVT_ID ETL_EXTRACT_ID ETL_RESOURCE_ID ETL_DIGEST_CD 
        SOURCE_SYSTEM_CD;
/* List of target columns to keep  */ 
%let keep = MONTH_NBR MONTH_NAME QRTR_NBR HALF_YEAR_NBR YEAR_NBR MONTH_LEN 
        MONTH_ID STEP_EVT_ID ETL_EXTRACT_ID ETL_RESOURCE_ID ETL_DIGEST_CD 
        SOURCE_SYSTEM_CD;
/*****************************************************************
*  ВЕРСИЯ:
*     $Id: transform_archive_put.sas 2517:eb3f59b6fe1d 2013-11-15 11:46:40Z rusane $
*
******************************************************************
*  НАЗНАЧЕНИЕ:
*     Размещает выгруженный набор в архиве, регистрирует выгрузку в реестре.
*
*  ПАРАМЕТРЫ:
*     tpInData             +  имя входного набора, выгруженной таблицы
*     tpInRegistry         -  имя входного набора, списка обновляемых записей в реестре
*                             Если не задан, то будет определен по архивной таблице
*     tpOut                +  имя выходного набора, архивной таблицы
*
******************************************************************/

%macro transform_archive_put;
   %etl_archive_put (
      mpInData                =  &tpInData,
      mpInRegistry            =
                                 %if &_INPUT_count ge 2 %then %do;
                                    &tpInRegistry
                                 %end;
                                 ,
      mpOut                   =  &tpOut
   );
%mend transform_archive_put;

%transform_archive_put;


%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end Разместить выгрузку в архиве **/

/*==========================================================================* 
 * Step:            Завершить модуль                      A52HJCF1.AT0020PQ * 
 * Transform:       Завершить модуль                                        * 
 * Description:                                                             * 
 *==========================================================================*/ 

%let transformID = %quote(A52HJCF1.AT0020PQ);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let _INPUT_count = 0; 
%let _OUTPUT_count = 0; 


/*****************************************************************
* ВЕРСИЯ:
*   $Id: transform_job_finish.sas 4063:34040bca471f 2015-06-19 09:28:58Z rusane $
*
******************************************************************
* НАЗНАЧЕНИЕ:
*   Регистрирует конец модуля ETL.
*
* ПАРАМЕТРЫ:
*   нет
*
******************************************************************/

%macro transform_job_finish;
   %etl_job_finish;
%mend transform_job_finish;

%transform_job_finish;


%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end Завершить модуль **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

